### PR TITLE
chore: update of dependency by renovate

### PR DESCRIPTION
**Pull request by gdrenovate**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [nginxinc/nginx-unprivileged](https://togithub.com/nginxinc/docker-nginx-unprivileged) | final | patch | `1.25.1` -> `1.25.3` |

---

### Release Notes

<details>
<summary>nginxinc/docker-nginx-unprivileged (nginxinc/nginx-unprivileged)</summary>

### [`v1.25.3`](https://togithub.com/nginxinc/docker-nginx-unprivileged/releases/tag/1.25.3)

[Compare Source](https://togithub.com/nginxinc/docker-nginx-unprivileged/compare/1.25.2...1.25.3)

NGINX 1.25.3 (mainline)

### [`v1.25.2`](https://togithub.com/nginxinc/docker-nginx-unprivileged/releases/tag/1.25.2)

[Compare Source](https://togithub.com/nginxinc/docker-nginx-unprivileged/compare/1.25.1...1.25.2)

NGINX 1.25.2 (mainline)

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/15341/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/16871/ : SUCCESS in 7m 29s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/16726/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/18171/ : SUCCESS in 7m 58s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR4019

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/3797/ : SUCCESS in 11m 40s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/19247/ : SUCCESS in 5m 18s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-pipeline/1440/ : SUCCESS in 10m 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/4965/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/1676/ : FAILURE in 1m 22s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-pipeline/1425/ : SUCCESS in 13m 18s

**Pull request merged**
