### PR TITLE
FEATURE MPNT-159, MPNT-169: Define feature flag enableMSSQLDataSource, Make UI SDK tiger client reflect the new MSSQL database types

### PR DESCRIPTION
**Pull request by thongdq**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10268/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12249/ : SUCCESS in 24m 34s

**Comment by thongdq** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizingReset.spec.ts**|15|-|40.3440s|
|✅|**dateFilter.spec.ts**|9|-|14.1700s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.0450s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|15.2610s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.5030s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.2800s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|20.0850s|
|✅|**dashboard.spec.ts**|9|-|51.7360s|
|✅|**attributeFilterButton.spec.ts**|9|-|30.9980s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.0630s|
|✅|**barChartDrilling.spec.ts**|4|-|6.6050s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.2030s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.1980s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.0450s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/321/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10269/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/321/ : SUCCESS in 13m 00s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3123

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/1/ : FAILURE in 3m 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3267/ : SUCCESS in 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2114/ : SUCCESS in 18m 54s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12252/ : SUCCESS in 14m 44s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3123

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/3/ : FAILURE in 3m 38s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3269/ : SUCCESS in 22s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2116/ : SUCCESS in 19m 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12256/ : SUCCESS in 16m 24s

**Pull request merged**
