### PR TITLE
feat: fetch catalog attributes in parallel

### PR DESCRIPTION
**Pull request by pbenes**
- introduce new metadata util to fetch all elements in parallel
- use this method on places where catalog attributes are fetched

risk: low
JIRA: STL-851

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Comment by pbenes** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|27.197s|
|✅|**dashboardBasicActions.spec.ts**|2|-|30.953s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|26.211s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|12.529s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|44.842s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|15.419s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|165.219s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|47.471s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|23.187s|
|✅|**hideFilters.spec.ts**|20|-|160.499s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|41.626s|
|✅|**multipleDateFilters.spec.ts**|5|-|43.592s|
|✅|**unknownVisualization.spec.ts**|1|-|7.091s|
|✅|**manyData.spec.ts**|2|-|14.466s|
|✅|**scatterPlot.spec.ts**|2|-|10.422s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/204/).

**Comment by pbenes** [comment]
extended test - tiger-cypress - isolated

**Comment by pbenes** [comment]
extended test - tiger-cypress - isolated

**Review by kandl — APPROVED** [review]
LGTM

**Review by xMort — APPROVED** [review]

**Pull request merged**
