### PR TITLE
Test e2e

### PR DESCRIPTION
**Pull request by ivanmjartan**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.1680s|
|✅|**dashboard.spec.ts**|9|-|56.1690s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0760s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.0030s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.5750s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.1500s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.1710s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.1730s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.2970s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|137.6190s|
|✅|**barChartDrilling.spec.ts**|4|-|5.7040s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.4540s|
|✅|**attributeFilterButton.spec.ts**|13|-|48.3440s|
|✅|**attributeFilter.spec.ts**|1|-|5.8940s|
|✅|**dateFilter.spec.ts**|9|-|14.1950s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.6120s|
|✅|**dashboardDnD.spec.ts**|7|-|54.8390s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.1040s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.6340s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.9300s|
|✅|**dashboardKPI.spec.ts**|8|-|134.6520s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/428/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.1680s|
|✅|**dashboard.spec.ts**|9|-|56.1690s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0760s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.0030s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.5750s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.1500s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.1710s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.1730s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.2970s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|137.6190s|
|✅|**barChartDrilling.spec.ts**|4|-|5.7040s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.4540s|
|✅|**attributeFilterButton.spec.ts**|13|-|48.3440s|
|✅|**attributeFilter.spec.ts**|1|-|5.8940s|
|✅|**dateFilter.spec.ts**|9|-|14.1950s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.6120s|
|✅|**dashboardDnD.spec.ts**|7|-|54.8390s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.1040s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.6340s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.9300s|
|✅|**dashboardKPI.spec.ts**|8|-|134.6520s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/428/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11902/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/137/ : SUCCESS in 21m 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11901/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13925/ : SUCCESS in 21m 16s

**Comment by ivanmjartan** [comment]
extended test - tiger-cypress - isolated

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11913/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/141/ : FAILURE in 10m 55s

**Pull request closed without merging**
