### PR TITLE
trivial: alerting and scheduling are by default on

### PR DESCRIPTION
**Pull request by hackerstanislav**
JIRA: F1-529

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Review by kandl — DISMISSED** [review]
LGTM

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - record

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|15.044s|
|✅|**dashboardBasicActions.spec.ts**|2|-|19.433s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|16.911s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|9.642s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|32.056s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|8.946s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|105.723s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|40.419s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|25.204s|
|✅|**hideFilters.spec.ts**|20|-|168.732s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|42.095s|
|✅|**multipleDateFilters.spec.ts**|5|-|41.822s|
|✅|**unknownVisualization.spec.ts**|1|-|5.813s|
|✅|**manyData.spec.ts**|2|-|11.926s|
|✅|**scatterPlot.spec.ts**|2|-|8.425s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/201/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|16.910s|
|✅|**dashboardBasicActions.spec.ts**|2|-|19.178s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|19.149s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|9.673s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|33.544s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|10.595s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|115.527s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|29.241s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|18.923s|
|✅|**hideFilters.spec.ts**|20|-|172.101s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|45.489s|
|✅|**multipleDateFilters.spec.ts**|5|-|45.134s|
|✅|**unknownVisualization.spec.ts**|1|-|6.998s|
|✅|**manyData.spec.ts**|2|-|15.455s|
|✅|**scatterPlot.spec.ts**|2|-|10.183s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/202/).

**Review by kandl — APPROVED** [review]
LGTM

**Pull request merged**
