### PR TITLE
RELATED: RAIL-2928 Implement LRUCache and use it

### PR DESCRIPTION
**Pull request by no23reason**
Since the lru-cache in version 4 (the last compatible with IE11) needs
specific setup when used with Webpack 5 (process polyfills), it makes
GoodData.UI unusable with create-react-app 5 that migrated to Webpack 5
and makes it impossible to alter these settings out of the box.

As a workaround, we wanted to migrate to another LRU implementation,
however none of the reasonably used existing implementations were good
for our particular use cases (IE11 support and maxAge):

* quick-lru: does not support IE11 because it uses generators.
  Older versions do not have maxAge which we need
* tiny-lru: does not work with cache size 1 (I sent a PR to fix that
  but I do not expect that to be merged, the package is quite stale)
* hashlru: does not have maxAge

So I ended up implementing a LRU cache in our code base. The code uses
the hashlru algorithm and is heavily inspired by quick-lru (which we
should migrate to once IE11 is dropped and get rid of the version
added in this commit).

One particular caveat of the hashlru algorithm (that is not that
important in my opinion) is that the maxSize is not precise:
the cache can hold more keys than the maxSize, but not by much (it very
much depends on the particular sequence of inserts and evicts). It will,
however, never be more than twice the maxSize. Since we use the maxSize
as more of a "do not cache millions of items here" kind of mechanism,
I think this caveat is ok for us given the performance gains
and relative code simplicity.

JIRA: RAIL-2928

---

Supported PR commands:

| Command                  | Description            |
| ------------------------ | ---------------------- |
| `ok to test`             | Re-run standard checks |
| `extended test`          | BackstopJS tests       |
| `extended check sonar`   | SonarQube tests        |
| `extended check cypress` | Cypress E2E tests      |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6252/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8042/ : SUCCESS in 16m 40s

**Review by plavemar — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2055

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/1804/ : SUCCESS in 5m 04s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2085/ : SUCCESS in 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/886/ : SUCCESS in 17m 31s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8046/ : SUCCESS in 19m 46s

**Pull request merged**
