### PR TITLE
RELATED: RAIL-2651 add hour and minute date granularities

### PR DESCRIPTION
**Pull request by jaceksan**
Only into Tiger backend

JIRA: RAIL-2651

Add hour / minute chronological granularities
- YYYY-MM-DD HH24
- YYYY-MM-DD HH24:MI

Add hour / minute periodical granularities
- hour in day - 00-23
- minute in hour - 00-59

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/570/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2162/ : SUCCESS in 11m 04s

**Review by no23reason — APPROVED** [review]
LGTM

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/302/ : SUCCESS in 25s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/558/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2182/ : SUCCESS in 9m 00s

**Pull request merged**
