### PR TITLE
chore(deps): update nginxinc/nginx-unprivileged docker tag to v1.23.3

### PR DESCRIPTION
**Pull request by yenkins-admin**
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| nginxinc/nginx-unprivileged | final | minor | `1.21.6` -> `1.23.3` |

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Review by andriichumak — APPROVED** [review]

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3580

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.3850s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.2110s|
|✅|**dashboardDnD.spec.ts**|7|-|55.7090s|
|✅|**dashboard.spec.ts**|9|-|59.5540s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|12.9900s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.3220s|
|✅|**attributeFilter.spec.ts**|1|-|7.5550s|
|✅|**attributeFilterButton.spec.ts**|13|-|49.4400s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.2120s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|94.0760s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.3590s|
|✅|**dashboardDateRelated.spec.ts**|8|-|64.5670s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.8880s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.4410s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.5300s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.7960s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.9390s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.7910s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.1340s|
|✅|**barChartDrilling.spec.ts**|4|-|5.8510s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.9730s|
|✅|**dateFilter.spec.ts**|9|-|15.0440s|
|✅|**dashboardKPI.spec.ts**|8|-|134.7030s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/484/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/101/ : SUCCESS in 8m 07s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/428/ : FAILURE in 1m 51s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14108/ : SUCCESS in 8m 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3701/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2545/ : SUCCESS in 12m 04s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/484/ : SUCCESS in 21m 29s (non-voting)

**Pull request merged**
