### PR TITLE
FEATURE: TNT-523 update localisations

### PR DESCRIPTION
**Pull request by NestorEncinas**
JIRA: TNT-523

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by oleg-morozov** [comment]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headerSection.spec.ts**|4(1 skipped)|-|62.1600s|
|✅|**dashboardBasicActions.spec.ts**|2|-|15.7040s|
|✅|**insightOnDashboard.spec.ts**|6(1 skipped)|-|42.1920s|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|25.0650s|
|✅|**dragDropAndMoveWidget.spec.ts**|3(1 skipped)|-|42.0100s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/117/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.9480s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.5520s|
|✅|**barChartDrilling.spec.ts**|4|-|6.1770s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.5600s|
|✅|**dashboardDnD.spec.ts**|7|-|57.4070s|
|✅|**dashboard.spec.ts**|9|-|56.8100s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.3250s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.1080s|
|✅|**attributeFilter.spec.ts**|1|-|8.0710s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.6530s|
|✅|**dateFilter.spec.ts**|9|-|13.7180s|
|✅|**dashboardKPI.spec.ts**|8|-|149.7760s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|8.2610s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.3980s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|88.3420s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.8240s|
|✅|**attributeFilterButton.spec.ts**|13|-|49.5040s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.0500s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.5420s|
|✅|**dashboardDateRelated.spec.ts**|8|-|63.9400s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|151.3080s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.4750s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/500/).

**Pull request merged**
