### PR TITLE
RELATED: RAIL-4041 AttributeFilterButton tests

### PR DESCRIPTION
**Pull request by plavemar**
JIRA: RAIL-4041

---

Supported PR commands:

| Command                  | Description            |
| ------------------------ | ---------------------- |
| `ok to test`             | Re-run standard checks |
| `extended test`          | BackstopJS tests       |
| `extended check sonar`   | SonarQube tests        |
| `extended check cypress` | Cypress E2E tests      |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by plavemar** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6896/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/123/ : SUCCESS in 8m 11s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6897/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8785/ : SUCCESS in 13m 29s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6906/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8793/ : SUCCESS in 13m 42s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6914/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/125/ : FAILURE in 5m 01s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by plavemar** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6915/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8799/ : SUCCESS in 15m 44s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButton.spec.ts**|9|-|40.5960s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|10.0510s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/126//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.6470s|
|✅|**drilling.spec.ts**|2|-|20.9640s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|18.5470s|
|✅|**dashboard.spec.ts**|9|-|65.3410s|
|✅|**dateFilter.spec.ts**|7|-|15.6540s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/126/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6916/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/126/ : UNSTABLE in 15m 55s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|10.9030s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|20.4490s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/127//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.7930s|
|✅|**attributeFilterButton.spec.ts**|9|-|34.5680s|
|✅|**dashboard.spec.ts**|9|-|52.8720s|
|✅|**dateFilter.spec.ts**|7|-|14.2230s|
|✅|**drilling.spec.ts**|2|-|18.1210s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/127/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6918/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/127/ : UNSTABLE in 10m 21s

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|26.2570s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/128//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**drilling.spec.ts**|2|-|20.8800s|
|✅|**attributeFilterButton.spec.ts**|9|-|45.9750s|
|✅|**dateFilter.spec.ts**|7|-|24.9790s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|26.2510s|
|✅|**dashboard.spec.ts**|9|-|57.0060s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|17.1210s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/128/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6924/ : SUCCESS in 17s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/128/ : UNSTABLE in 14m 21s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/129//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|25.7420s|
|✅|**dashboard.spec.ts**|9|-|63.1890s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|19.7910s|
|✅|**drilling.spec.ts**|2|-|26.1700s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|16.9130s|
|✅|**attributeFilterButton.spec.ts**|9|-|41.3180s|
|❌|**[🎥 dateFilter.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/129//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dateFilter.spec.ts.mp4)**|7|<span style="color: red">1</span>|22.6910s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/129/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6927/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/129/ : UNSTABLE in 16m 57s

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButton.spec.ts**|9|-|35.8490s|
|✅|**drilling.spec.ts**|2|-|19.5690s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.2900s|
|✅|**dateFilter.spec.ts**|7|-|15.7130s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/132//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**dashboard.spec.ts**|9|-|55.2230s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|20.4090s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.7020s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/132/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6936/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/132/ : UNSTABLE in 12m 49s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6935/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8812/ : SUCCESS in 14m 43s

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboard.spec.ts**|9|-|57.7550s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|21.4850s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|21.1060s|
|✅|**dateFilter.spec.ts**|7|-|18.4810s|
|✅|**attributeFilterButton.spec.ts**|9|-|36.0890s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|12.0060s|
|✅|**drilling.spec.ts**|2|-|20.4430s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/133//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/133/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6944/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/133/ : UNSTABLE in 14m 11s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by plavemar** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6947/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8821/ : FAILURE in 2m 01s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6948/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/134/ : UNSTABLE in 10m 26s

**Comment by plavemar** [comment]
extended check cypress

**Comment by plavemar** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by plavemar** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6959/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8828/ : SUCCESS in 14m 26s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6960/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/138/ : UNSTABLE in 17m 20s

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButton.spec.ts**|9|-|33.6280s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/139//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**dateFilter.spec.ts**|7|-|14.4550s|
|✅|**dashboard.spec.ts**|9|-|53.1950s|
|✅|**drilling.spec.ts**|2|-|18.6280s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.9360s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|21.9930s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|9.9610s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/139/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6978/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/139/ : UNSTABLE in 10m 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6977/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8842/ : SUCCESS in 13m 39s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 dateFilter.spec.ts](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/2//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dateFilter.spec.ts.mp4)**|7|<span style="color: red">1</span>|22.7690s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|26.2960s|
|✅|**drilling.spec.ts**|2|-|26.2710s|
|✅|**attributeFilterButton.spec.ts**|9|-|69.7360s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|29.7330s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/2//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**dashboard.spec.ts**|9|-|66.0290s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|16.3860s|

You can find full report [here](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/2/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|29.8490s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|16.7810s|
|❌|**[🎥 dateFilter.spec.ts](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/3//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dateFilter.spec.ts.mp4)**|7|<span style="color: red">1</span>|23.3250s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/3//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButton.spec.ts**|9|-|44.4270s|
|✅|**drilling.spec.ts**|2|-|26.6950s|
|✅|**dashboard.spec.ts**|9|-|65.6870s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|24.9070s|

You can find full report [here](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/3/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|7|-|23.4980s|
|✅|**drilling.spec.ts**|2|-|26.8790s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|16.4490s|
|✅|**attributeFilterButton.spec.ts**|9|-|43.5890s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|24.7060s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/4//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**dashboard.spec.ts**|9|-|66.5880s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|28.5090s|

You can find full report [here](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/4/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/141//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButton.spec.ts**|9|-|35.4660s|
|✅|**dateFilter.spec.ts**|7|-|15.9440s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.1690s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|18.9350s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.2140s|
|✅|**drilling.spec.ts**|2|-|19.5450s|
|✅|**dashboard.spec.ts**|9|-|55.2430s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/141/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/6999/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/141/ : UNSTABLE in 13m 59s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7002/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8870/ : SUCCESS in 16m 20s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 dateFilter.spec.ts](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/5//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dateFilter.spec.ts.mp4)**|7|<span style="color: red">1</span>|22.5700s|
|✅|**dashboard.spec.ts**|9|-|65.4050s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/5//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardFiltering.spec.ts.mp4)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|25.3560s|
|✅|**attributeFilterButton.spec.ts**|9|-|43.1100s|
|✅|**drilling.spec.ts**|2|-|26.9700s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|16.6250s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|29.1300s|

You can find full report [here](https://cing-dev.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/5/).

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButton.spec.ts**|9|-|33.2900s|
|✅|**dashboard.spec.ts**|9|-|52.9970s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|21.0720s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.6700s|
|✅|**dateFilter.spec.ts**|7|-|14.2550s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/142/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**drilling.spec.ts**|2|-|18.1830s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|9.8980s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/142/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7005/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/142/ : UNSTABLE in 10m 09s

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|9.8250s|
|✅|**dateFilter.spec.ts**|7|-|14.3330s|
|✅|**drilling.spec.ts**|2|-|19.1350s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|21.7260s|
|✅|**dashboard.spec.ts**|9|-|53.2990s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/144/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButton.spec.ts**|9|-|33.4200s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.7540s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/144/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7027/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/144/ : UNSTABLE in 10m 13s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7026/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8888/ : SUCCESS in 16m 14s

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 dateFilter.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/145/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|7|<span style="color: red">1</span>|15.3590s|
|✅|**attributeFilterButton.spec.ts**|9|-|36.6890s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.4590s|
|✅|**drilling.spec.ts**|2|-|19.5550s|
|✅|**dashboard.spec.ts**|9|-|54.5030s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/145/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.6280s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|12.0770s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/145/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7031/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/145/ : UNSTABLE in 13m 01s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7030/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8890/ : SUCCESS in 13m 42s

**Comment by plavemar** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardFiltering.spec.ts**|2|-|24.2270s|
|✅|**attributeFilterButton.spec.ts**|9|-|36.4230s|
|✅|**dashboard.spec.ts**|9|-|54.7530s|
|✅|**drilling.spec.ts**|2|-|19.6630s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.9740s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.6370s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.5450s|
|✅|**dateFilter.spec.ts**|7|-|16.3080s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/148/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7047/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/148/ : SUCCESS in 10m 38s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/7046/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8899/ : SUCCESS in 16m 57s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2040/ : SUCCESS in 10m 22s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2323/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1136/ : SUCCESS in 15m 18s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/8904/ : SUCCESS in 16m 02s

**Pull request merged**
