### PR TITLE
Tiger OpenAPI settings resolver without workspace

### PR DESCRIPTION
**Pull request by oleg-morozov**
JIRA: TNT-1033

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by oleg-morozov** [comment]
extended test

**Comment by oleg-morozov** [comment]
extended check cypress

**Comment by oleg-morozov** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/38/ : UNSTABLE in 14m 53s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9676/ : SUCCESS in 5s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-check-extended-sonar-PR2954

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9674/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1883/ : SUCCESS in 16m 05s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButton.spec.ts**|9|-|38.0550s|
|❌|**[🎥 dateFilter.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/290/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">2</span>|19.6960s|
|❌|**[🎥 drilling.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/290/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.3870s|
|✅|**barChartDrilling.spec.ts**|4|-|12.1790s|
|✅|**pivotTableSizing.spec.ts**|1|-|10.4380s|
|❌|**[🎥 attributeFilterConfig.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/290/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|27.0170s|
|❌|**[🎥 dashboard.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/290/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">9</span>|0.0000s|
|✅|**headlineChartDrilling.spec.ts**|2|-|9.3730s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|45.8960s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|24.7080s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|13.5000s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|20.2710s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/290/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|13.0310s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|12.9560s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/290/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9675/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/290/ : UNSTABLE in 20m 51s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1815/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9673/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1815/ : SUCCESS in 25m 55s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9677/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11558/ : FAILURE in 9m 21s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9682/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11563/ : SUCCESS in 14m 38s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by oleg-morozov** [comment]
extended test

**Comment by oleg-morozov** [comment]
extended check sonar

**Comment by oleg-morozov** [comment]
extended check cypress

**Comment by oleg-morozov** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/39/ : UNSTABLE in 12m 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9688/ : SUCCESS in 8s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-check-extended-sonar-PR2954

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9686/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1884/ : SUCCESS in 15m 53s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headlineChartDrilling.spec.ts**|2|-|9.0510s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.3030s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/291/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.8470s|
|✅|**barChartDrilling.spec.ts**|4|-|11.6040s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|44.2220s|
|✅|**attributeFilterButton.spec.ts**|9|-|44.9800s|
|✅|**pivotTableSizing.spec.ts**|1|-|10.2470s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|25.1070s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.3980s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.0270s|
|✅|**dateFilter.spec.ts**|9|-|20.1350s|
|❌|**[🎥 drilling.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/291/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.9310s|
|❌|**[🎥 attributeFilterConfig.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/291/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|
|❌|**[🎥 dashboard.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/291/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">9</span>|0.0000s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|12.5130s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/291/).

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1816/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9685/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1816/ : SUCCESS in 29m 38s

**Comment by oleg-morozov** [comment]
extended check cypress

**Comment by oleg-morozov** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/40/ : UNSTABLE in 14m 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9691/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9689/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11566/ : SUCCESS in 14m 41s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/292/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**pivotTableSizing.spec.ts**|1|-|9.7230s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|24.8380s|
|❌|**[🎥 dashboard.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/292/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">9</span>|0.0000s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|11.8080s|
|✅|**headlineChartDrilling.spec.ts**|2|-|9.2140s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|12.2450s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.3600s|
|❌|**[🎥 attributeFilterConfig.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/292/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|43.9170s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.9730s|
|✅|**attributeFilterButton.spec.ts**|9|-|37.1170s|
|✅|**dateFilter.spec.ts**|9|-|20.1160s|
|❌|**[🎥 drilling.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/292/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**barChartDrilling.spec.ts**|4|-|11.3470s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|12.4480s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.5690s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/292/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9690/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/292/ : UNSTABLE in 20m 14s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9692/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11567/ : SUCCESS in 14m 27s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2954

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2745/ : SUCCESS in 1m 00s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3048/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1888/ : SUCCESS in 17m 47s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11580/ : SUCCESS in 15m 11s

**Pull request merged**
