### PR TITLE
chore(deps): update wiremock/wiremock docker tag to v2.35.0

### PR DESCRIPTION
**Pull request by yenkins-admin**
This PR contains the following updates:

| Package | Update | Change |
|---|---|---|
| wiremock/wiremock | minor | `2.34.0` -> `2.35.0` |

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12110/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14076/ : SUCCESS in 6m 14s

**Comment by kandl** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6930s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.9800s|
|✅|**attributeFilter.spec.ts**|1|-|6.1380s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.9020s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.5980s|
|✅|**dashboardDnD.spec.ts**|7|-|55.8070s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.8180s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8700s|
|✅|**dashboardKPI.spec.ts**|8|-|135.9680s|
|✅|**dashboard.spec.ts**|9|-|56.1460s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0970s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.7140s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4760s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|87.3780s|
|✅|**dateFilter.spec.ts**|9|-|11.9280s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.0660s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.3600s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.9170s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.9540s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.8670s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|11.2020s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.6540s|
|✅|**dashboardDateRelated.spec.ts**|8|-|64.4910s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/475/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6930s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.9800s|
|✅|**attributeFilter.spec.ts**|1|-|6.1380s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.9020s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.5980s|
|✅|**dashboardDnD.spec.ts**|7|-|55.8070s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.8180s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8700s|
|✅|**dashboardKPI.spec.ts**|8|-|135.9680s|
|✅|**dashboard.spec.ts**|9|-|56.1460s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0970s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.7140s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4760s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|87.3780s|
|✅|**dateFilter.spec.ts**|9|-|11.9280s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.0660s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.3600s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.9170s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.9540s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.8670s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|11.2020s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.6540s|
|✅|**dashboardDateRelated.spec.ts**|8|-|64.4910s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/475/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12118/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/194/ : SUCCESS in 22m 50s

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/54/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|60.7300s|
|✅|**insightOnDashboard.spec.ts**|6(1 skipped)|-|92.9400s|
|✅|**dragDropAndMoveWidget.spec.ts**|3(1 skipped)|-|71.6380s|
|✅|**headerSection.spec.ts**|4(1 skipped)|-|93.1570s|
|✅|**dashboardBasicActions.spec.ts**|2|-|34.5030s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/54/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12119/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/195/ : SUCCESS in 12m 25s

**Pull request closed without merging**
