### PR TITLE
jsc test

### PR DESCRIPTION
**Pull request by scavnickyj**
---

Supported PR commands:

| Command                                               | Description                                                |
| ----------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                          | Re-run standard checks                                     |
| `extended check sonar`                                | SonarQube tests                                            |
| `extended check plugins`                              | Dashboard plugins tests                                    |
| `extended test - backstop`                            | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                |                                                            |
| `extended test - tiger-cypress - isolated <testName>` | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`   | Create a new recording for isolated Tiger tests.           |
| **E2E Cypress tests commands - BEAR**                 |                                                            |
| `extended test - cypress - isolated <testName>`       | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`         | Create a new recording for isolated Bear tests.            |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headerSection.spec.ts**|4(1 skipped)|-|71.3570s|
|❌|**[🎥 insightOnDashboard.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-docker/34//artifact/libs/sdk-ui-tests-e2e/cypress/videos/insightOnDashboard.spec.ts.mp4)**|6(1 skipped)|<span style="color: red">2</span>|82.5930s|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|26.0640s|
|✅|**dragDropAndMoveWidget.spec.ts**|3(1 skipped)|-|45.5970s|
|✅|**dashboardBasicActions.spec.ts**|2|-|17.5220s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-docker/34/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/114/ : FAILURE in 14m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11321/ : SUCCESS in 11s

**Comment by scavnickyj** [comment]
extended test - cypress - isolated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11322/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13397/ : SUCCESS in 42m 11s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|219.6190s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|31.1800s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.1950s|
|✅|**headlineChartDrilling.spec.ts**|2|-|7.0040s|
|✅|**barChartDrilling.spec.ts**|4|-|11.5850s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|26.4610s|
|✅|**dashboardKPI.spec.ts**|8|-|210.2040s|
|✅|**attributeFilterButton.spec.ts**|9|-|54.4970s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|69.9410s|
|✅|**dashboardDnD.spec.ts**|7|-|88.8270s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|12.3240s|
|✅|**dashboard.spec.ts**|9|-|141.9390s|
|✅|**dashboardDateRelated.spec.ts**|8|-|169.0500s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|57.5040s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|11.8120s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|25.9910s|
|✅|**dateFilter.spec.ts**|9|-|27.5140s|
|✅|**dashboardDependentFilter.spec.ts**|4|-|95.2930s|
|✅|**pivotTableSizing.spec.ts**|1|-|8.2650s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|12.6270s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/385/).

**Comment by scavnickyj** [comment]
extended test - cypress - record

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/119/ : FAILURE in 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11331/ : SUCCESS in 7s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11330/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13404/ : SUCCESS in 17m 57s

**Pull request closed without merging**
