### PR TITLE
Empty

### PR DESCRIPTION
**Pull request by oleg-morozov**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by oleg-morozov** [comment]
extended check cypress

**Comment by oleg-morozov** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9693/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11568/ : SUCCESS in 8m 00s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/41/ : UNSTABLE in 12m 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9695/ : SUCCESS in 7s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizingReset.spec.ts**|15|-|48.3620s|
|✅|**pivotTableSizing.spec.ts**|1|-|12.0300s|
|✅|**dateFilter.spec.ts**|9|-|24.4540s|
|❌|**[🎥 dashboard.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/293/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">9</span>|0.0000s|
|✅|**attributeFilterButton.spec.ts**|9|-|40.8590s|
|✅|**barChartDrilling.spec.ts**|4|-|14.2430s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|29.8490s|
|❌|**[🎥 drilling.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/293/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|❌|**[🎥 attributeFilterConfig.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/293/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|22.3710s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|14.5090s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|14.5670s|
|❌|**[🎥 dashboardFiltering.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/293/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|✅|**headlineChartDrilling.spec.ts**|2|-|11.0400s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|14.6540s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|25.8240s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|14.2510s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/293/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9694/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/293/ : UNSTABLE in 21m 22s

**Pull request closed without merging**
