### PR TITLE
BUGFIX: QA-18367 Fix unstable Drilling and DashboardKPI tests

### PR DESCRIPTION
**Pull request by NghiLamGD**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by NghiLamGD** [comment]
extended test - cypress - isolated drilling.spec.ts,dashboardKPI.spec.ts

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12043/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14019/ : SUCCESS in 6m 42s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.3060s|
|✅|**dashboardKPI.spec.ts**|8|-|130.9700s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/460/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.3060s|
|✅|**dashboardKPI.spec.ts**|8|-|130.9700s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/460/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12044/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/177/ : SUCCESS in 8m 03s

**Review by hungnguyenauto — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3567

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.1190s|
|✅|**dashboardKPI.spec.ts**|8|-|150.3090s|
|✅|**attributeFilter.spec.ts**|1|-|7.6040s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.3150s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.1160s|
|✅|**dashboard.spec.ts**|9|-|57.6210s|
|✅|**dashboardDateRelated.spec.ts**|8|-|66.5010s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.2860s|
|✅|**dashboardDnD.spec.ts**|7|-|56.0820s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.3280s|
|✅|**dateFilter.spec.ts**|9|-|12.8060s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.1090s|
|✅|**barChartDrilling.spec.ts**|4|-|5.7510s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.1430s|
|✅|**attributeFilterButton.spec.ts**|13|-|50.4650s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.7680s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|88.5930s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.4310s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|144.4030s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|41.4090s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0320s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/461/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/82/ : FAILURE in 10m 30s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/412/ : FAILURE in 1m 37s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14021/ : SUCCESS in 6m 44s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3685/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2528/ : SUCCESS in 10m 56s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/461/ : SUCCESS in 22m 17s (non-voting)

**Pull request merged**
