### PR TITLE
feat: in-platform notification channels

### PR DESCRIPTION
**Pull request by kandl**
- Add new feature flag for in-platform notification channels.
- Hide in-platform notification channels behind the feature flag.
- Add `assertNever` utility type for safe exhaustiveness checks.
- Align notification channels with our model/spi conventions.
- Add possibility to query / filter notification channels.
- Make convertors safer (when converting unknown notification channel, it's filtered now - before it thrown error).
- Adjust all usages of notification channels to new model.

risk: low
JIRA: F1-928

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Review by hackerstanislav — DISMISSED** [review]

**Review by hackerstanislav — APPROVED** [review]

**Review by hackerstanislav — APPROVED** [review]

**Comment by kandl** [comment]
extended test - tiger-cypress - record

**Comment by kandl** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/221/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|14.988s|
|✅|**dashboardBasicActions.spec.ts**|2|-|13.650s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|13.884s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|8.114s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|25.563s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|10.082s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|98.465s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|23.511s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|13.259s|
|✅|**hideFilters.spec.ts**|12|-|76.977s|
|✅|**hideFiltersTooltips.spec.ts**|8|-|60.771s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|35.276s|
|✅|**multipleDateFilters.spec.ts**|5|-|34.740s|
|✅|**unknownVisualization.spec.ts**|1|-|5.842s|
|✅|**manyData.spec.ts**|2|-|11.575s|
|✅|**scatterPlot.spec.ts**|2|-|8.211s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/221/).

**Comment by kandl** [comment]
extended test - tiger-cypress - isolated

**Pull request merged**
