### PR TITLE
RELATED: F1-645 new package

### PR DESCRIPTION
**Pull request by andriichumak**
- introduce new gen-ai package
- add backend support for the gen-ai
- introduce basic UI
- 
---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Comment by andriichumak** [comment]
extended test - backstop

**Comment by andriichumak** [comment]
extended test - backstop

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/2710/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by andriichumak** [comment]
extended test - backstop

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/2711/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by andriichumak** [comment]
Looks like backstop in not stable. Tried it a few times, each time a different error, not related to my PR.

**Review by ivan-nejezchleb — APPROVED** [review]

**Pull request merged**
