### PR TITLE
BUGFIX: TNT-1401 icon tooltip not showing

### PR DESCRIPTION
**Pull request by NestorEncinas**
JIRA: TNT-1401

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by NestorEncinas** [comment]
extended test - backstop

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11868/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13898/ : SUCCESS in 11m 16s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1980/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11869/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/131/ : SUCCESS in 21m 27s

**Comment by NestorEncinas** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8200s|
|✅|**attributeFilter.spec.ts**|1|-|5.8990s|
|✅|**attributeFilterButton.spec.ts**|13|-|46.9290s|
|✅|**dashboardDnD.spec.ts**|7|-|55.7440s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0630s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.0110s|
|✅|**dashboard.spec.ts**|9|-|56.1260s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.9620s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4730s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.6670s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.5440s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0690s|
|✅|**dashboardKPI.spec.ts**|8|-|130.0530s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.3710s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|136.9300s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8160s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|35.7410s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8550s|
|✅|**dateFilter.spec.ts**|9|-|11.5490s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7610s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6000s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/422/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8200s|
|✅|**attributeFilter.spec.ts**|1|-|5.8990s|
|✅|**attributeFilterButton.spec.ts**|13|-|46.9290s|
|✅|**dashboardDnD.spec.ts**|7|-|55.7440s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0630s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.0110s|
|✅|**dashboard.spec.ts**|9|-|56.1260s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.9620s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4730s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.6670s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.5440s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0690s|
|✅|**dashboardKPI.spec.ts**|8|-|130.0530s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.3710s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|136.9300s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8160s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|35.7410s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8550s|
|✅|**dateFilter.spec.ts**|9|-|11.5490s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7610s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6000s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/422/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11870/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/132/ : SUCCESS in 20m 59s

**Comment by NestorEncinas** [comment]
extended test - backstop

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11871/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13899/ : SUCCESS in 12m 46s

**Comment by gdgate** [comment]
Build in pipeline check-extended aborted.

**Comment by NestorEncinas** [comment]
extended test - backstop

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11873/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13900/ : SUCCESS in 13m 09s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1981/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11874/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/133/ : UNSTABLE in 21m 56s

**Comment by NestorEncinas** [comment]
extended test - backstop

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11875/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13901/ : SUCCESS in 11m 27s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1982/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11876/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/134/ : SUCCESS in 23m 13s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3537

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/391/ : FAILURE in 1m 56s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3664/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2507/ : SUCCESS in 12m 05s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13902/ : SUCCESS in 11m 10s

**Pull request merged**
