### PR TITLE
RELATED: RAIL-4538 improve e2e tests

### PR DESCRIPTION
**Pull request by no23reason**
* upgrade Cypress to version 10
* fix existing tests
* make the e2e infrastructure runnable on Apple Silicon (including recordings refreshing)

Caveats:
* plugin tests were not migrated all the way to Cypress 10 as their future is uncertain and I did not want to invest in that

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.6140s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.4480s|
|✅|**headlineChartDrilling.spec.ts**|2|-|4.1890s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|21.6210s|
|✅|**barChartDrilling.spec.ts**|4|-|7.2540s|
|✅|**dashboard.spec.ts**|9|-|53.8930s|
|✅|**attributeFilterButton.spec.ts**|9|-|35.8720s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|36.7940s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.7360s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.0220s|
|✅|**dateFilter.spec.ts**|9|-|18.0780s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|8.7360s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.8920s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|19.2610s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/314/).

**Comment by no23reason** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/53/ : UNSTABLE in 18m 47s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10111/ : SUCCESS in 12s

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by no23reason** [comment]
extended check cypress

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by no23reason** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.5790s|
|✅|**attributeFilterButton.spec.ts**|9|-|36.8950s|
|✅|**headlineChartDrilling.spec.ts**|2|-|4.4210s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|43.6820s|
|✅|**dashboard.spec.ts**|9|-|55.3620s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.6550s|
|✅|**dateFilter.spec.ts**|9|-|21.8770s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|20.9170s|
|✅|**barChartDrilling.spec.ts**|4|-|8.3220s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|23.3570s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|10.8570s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.5540s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.5550s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|18.5150s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/315/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10114/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/315/ : SUCCESS in 14m 51s

**Comment by no23reason** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.5750s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|16.5520s|
|✅|**dashboard.spec.ts**|9|-|53.9020s|
|✅|**headlineChartDrilling.spec.ts**|2|-|4.3760s|
|✅|**barChartDrilling.spec.ts**|4|-|7.2180s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.5110s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|43.7060s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|21.9950s|
|✅|**dateFilter.spec.ts**|9|-|18.0750s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|18.8900s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.3580s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|8.0190s|
|✅|**attributeFilterButton.spec.ts**|9|-|35.2610s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|8.8190s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/316/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10117/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/316/ : SUCCESS in 13m 15s

**Comment by no23reason** [comment]
extended check plugins

**Comment by no23reason** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10120/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12103/ : SUCCESS in 21m 09s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3085

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2923/ : FAILURE in 2m 39s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3229/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2071/ : SUCCESS in 15m 46s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12111/ : SUCCESS in 20m 01s

**Pull request merged**
