### PR TITLE
MPNT-164 Make UI SDK tiger client reflect the new GreenPlum db type

### PR DESCRIPTION
**Pull request by lamho-gooddata**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10174/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12150/ : FAILURE in 8m 02s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10180/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12156/ : SUCCESS in 15m 06s

**Comment by lamho-gooddata** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10184/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12160/ : SUCCESS in 16m 34s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1853/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10186/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1853/ : UNSTABLE in 29m 29s

**Comment by lamho-gooddata** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-check-extended-sonar-PR3097

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by lamho-gooddata** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|8.4320s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|8.7000s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|9.9260s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|23.7990s|
|✅|**pivotTableSizing.spec.ts**|1|-|6.7950s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|20.6790s|
|✅|**headlineChartDrilling.spec.ts**|2|-|5.5960s|
|✅|**barChartDrilling.spec.ts**|4|-|9.1380s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.0660s|
|✅|**attributeFilterButton.spec.ts**|9|-|37.9890s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|47.3650s|
|✅|**dashboard.spec.ts**|9|-|57.0920s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|8.2920s|
|✅|**dateFilter.spec.ts**|9|-|19.9790s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/319/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10192/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/319/ : SUCCESS in 15m 35s

**Comment by lamho-gooddata** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/59/ : UNSTABLE in 13m 52s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10193/ : SUCCESS in 6s

**Comment by lamho-gooddata** [comment]
extended test

**Comment by lamho-gooddata** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/60/ : UNSTABLE in 16m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10195/ : SUCCESS in 7s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1854/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10194/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1854/ : UNSTABLE in 29m 07s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10225/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12201/ : SUCCESS in 18m 44s

**Comment by lamho-gooddata** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10227/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12202/ : SUCCESS in 17m 14s

**Comment by lamho-gooddata** [comment]
extended test

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1861/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10229/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1861/ : UNSTABLE in 33m 09s

**Comment by lamho-gooddata** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-check-extended-sonar-PR3097

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10235/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2099/ : SUCCESS in 17m 14s

**Comment by lamho-gooddata** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|23.3420s|
|✅|**dashboard.spec.ts**|9|-|54.7590s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.5960s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.8990s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|8.5810s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|44.7730s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|9.7810s|
|✅|**attributeFilterButton.spec.ts**|9|-|37.6300s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.5300s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|20.1920s|
|✅|**headlineChartDrilling.spec.ts**|2|-|4.3270s|
|✅|**dateFilter.spec.ts**|9|-|18.0900s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|16.7910s|
|✅|**barChartDrilling.spec.ts**|4|-|7.1960s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/320/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10238/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/320/ : SUCCESS in 14m 12s

**Comment by lamho-gooddata** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/61/ : UNSTABLE in 13m 08s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10239/ : SUCCESS in 9s

**Review by ivan-nejezchleb — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2948/ : FAILURE in 2m 08s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3254/ : SUCCESS in 46s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2101/ : SUCCESS in 20m 25s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12215/ : SUCCESS in 25m 25s

**Pull request merged**
