### PR TITLE
RELATED: FET-1152 Remove plugin tests

### PR DESCRIPTION
**Pull request by kandl**
- remove current dashboard plugin tests and related infra
- current infra will be replaced with tests running on top of KD
- reason for this change is that we need to test the integration part that is in KD, as this was the part causing the most issues

JIRA: FET-1152

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Review by ivanmjartan — APPROVED** [review]

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12100/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14063/ : SUCCESS in 15m 21s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dragDropAndMoveWidget.spec.ts**|3(1 skipped)|-|44.7390s|
|✅|**insightOnDashboard.spec.ts**|6(1 skipped)|-|42.6730s|
|✅|**headerSection.spec.ts**|4(1 skipped)|-|67.2860s|
|✅|**dashboardBasicActions.spec.ts**|2|-|15.3080s|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|28.5750s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/92/).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3574

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|13.1340s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.2580s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.0720s|
|✅|**dashboardKPI.spec.ts**|8|-|145.9930s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.4510s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.1750s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.1400s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|38.5350s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.9630s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.2460s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.0100s|
|✅|**attributeFilter.spec.ts**|1|-|6.1030s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.2160s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.9880s|
|✅|**barChartDrilling.spec.ts**|4|-|5.7010s|
|✅|**dashboardDateRelated.spec.ts**|8|-|60.9360s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.8360s|
|✅|**dashboardDnD.spec.ts**|7|-|55.8680s|
|✅|**dashboard.spec.ts**|9|-|55.2540s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.2330s|
|✅|**attributeFilterButton.spec.ts**|13|-|48.3850s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.2310s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|12.7080s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/471/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/92/ : SUCCESS in 8m 54s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/420/ : FAILURE in 2m 05s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14064/ : SUCCESS in 16m 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3693/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2536/ : SUCCESS in 10m 57s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/471/ : SUCCESS in 26m 26s (non-voting)

**Pull request merged**
