### PR TITLE
RELATED: RAIL-4538 fix existing e2e tests

### PR DESCRIPTION
**Pull request by no23reason**
- make the tests runnable locally without docker, this makes the setup easier to use
- fix typing and eslint issues in the e2e scenario app
- fix existing e2e tests

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by no23reason** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by no23reason** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10056/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12028/ : FAILURE in 27m 05s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 attributeFilterButtonParentChild.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/312/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|
|❌|**[🎥 attributeFilterButton.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/312/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">9</span>|0.0000s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|14.8660s|
|✅|**dateFilter.spec.ts**|9|-|44.6020s|
|✅|**pivotTableSizing.spec.ts**|1|-|14.5210s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|29.4890s|
|✅|**headlineChartDrilling.spec.ts**|2|-|10.8760s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|14.9890s|
|✅|**barChartDrilling.spec.ts**|4|-|22.0150s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|15.4570s|
|❌|**[🎥 attributeFilterButtonWithSelection.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/312/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2|<span style="color: red">2</span>|0.0000s|
|❌|**[🎥 dashboard.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/312/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">9</span>|0.0000s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|50.4320s|
|❌|**[🎥 parentChildFiltersWithPlaceholders.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/312/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/312/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10057/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/312/ : UNSTABLE in 30m 00s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10075/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12060/ : FAILURE in 22m 47s

**Comment by no23reason** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 pivotTableSizingReset.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/313/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|15(2 skipped)|<span style="color: red">13</span>|0.0000s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|15.0170s|
|✅|**headlineChartDrilling.spec.ts**|2|-|6.9260s|
|✅|**dateFilter.spec.ts**|9|-|30.0760s|
|✅|**barChartDrilling.spec.ts**|4|-|8.6760s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|36.6120s|
|✅|**attributeFilterButton.spec.ts**|9|-|50.1620s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|21.6160s|
|❌|**[🎥 pivotTableSizing.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/313/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|1|<span style="color: red">1</span>|0.0000s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|19.9010s|
|✅|**dashboard.spec.ts**|9|-|59.9250s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|10.1790s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|14.9890s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|14.7360s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/313/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10081/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/313/ : UNSTABLE in 18m 24s

**Pull request closed without merging**
