### PR TITLE
RELATED: RAIL-4538 Upgrade cypress to version 8

### PR DESCRIPTION
**Pull request by no23reason**
JIRA: RAIL-4538

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by no23reason** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|28.4870s|
|❌|**[🎥 attributeFilterButton.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/309/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9(2 skipped)|<span style="color: red">7</span>|0.0000s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|15.3160s|
|✅|**barChartDrilling.spec.ts**|4|-|15.5430s|
|❌|**[🎥 attributeFilterButtonWithSelection.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/309/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|2(1 skipped)|<span style="color: red">1</span>|0.0000s|
|❌|**[🎥 parentChildFiltersWithPlaceholders.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/309/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|
|✅|**headlineChartDrilling.spec.ts**|2|-|12.5670s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|15.1930s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|31.5720s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|16.0880s|
|❌|**[🎥 dashboard.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/309/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">9</span>|0.0000s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|46.6980s|
|❌|**[🎥 attributeFilterButtonParentChild.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/309/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|3|<span style="color: red">3</span>|0.0000s|
|✅|**pivotTableSizing.spec.ts**|1|-|13.4440s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/309/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9983/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/309/ : UNSTABLE in 23m 32s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9982/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11934/ : FAILURE in 27m 18s

**Pull request closed without merging**
