### PR TITLE
jsc test

### PR DESCRIPTION
**Pull request by scavnickyj**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by scavnickyj** [comment]
extended test

**Comment by scavnickyj** [comment]
extended check cypress

**Comment by scavnickyj** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9730/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11622/ : SUCCESS in 8m 14s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/42/ : UNSTABLE in 12m 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9733/ : SUCCESS in 6s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|26.9830s|
|✅|**attributeFilterConfig.spec.ts**|3|-|32.5260s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.8980s|
|✅|**dateFilter.spec.ts**|9|-|19.8190s|
|✅|**dashboardFiltering.spec.ts**|2|-|25.4770s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|20.0690s|
|✅|**dashboard.spec.ts**|9|-|54.5920s|
|✅|**barChartDrilling.spec.ts**|4|-|11.4220s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|39.0790s|
|✅|**attributeFilterButton.spec.ts**|9(2 skipped)|-|29.0190s|
|✅|**headlineChartDrilling.spec.ts**|2|-|8.8230s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2(1 skipped)|-|8.9480s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|12.5490s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.0770s|
|✅|**pivotTableSizing.spec.ts**|1|-|9.6420s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.0960s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/295/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9732/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/295/ : SUCCESS in 13m 42s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1817/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9731/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1817/ : SUCCESS in 26m 45s

**Comment by scavnickyj** [comment]
extended check cypress

**Comment by scavnickyj** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButton.spec.ts**|9(2 skipped)|-|31.7000s|
|✅|**dashboard.spec.ts**|9|-|57.0160s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|13.7360s|
|✅|**dateFilter.spec.ts**|9|-|23.1620s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2(1 skipped)|-|10.5520s|
|✅|**attributeFilterConfig.spec.ts**|3|-|35.1020s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|14.0120s|
|✅|**headlineChartDrilling.spec.ts**|2|-|10.6360s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|25.5090s|
|✅|**dashboardFiltering.spec.ts**|2|-|28.3150s|
|✅|**barChartDrilling.spec.ts**|4|-|13.3270s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|41.9130s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|13.8520s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|27.6850s|
|✅|**pivotTableSizing.spec.ts**|1|-|11.5270s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|21.6190s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/298/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9751/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/298/ : SUCCESS in 15m 28s

**Pull request closed without merging**
