### PR TITLE
FEATURE: TNT-1409 Single select filter with drilling

### PR DESCRIPTION
**Pull request by oleg-morozov**
Handle casting values into SSF via
drilling into dashboard.

JIRA: TNT-1409

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11879/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13903/ : FAILURE in 6m 31s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11881/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13905/ : SUCCESS in 16m 27s

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11905/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13926/ : SUCCESS in 16m 46s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11919/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13933/ : SUCCESS in 17m 12s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11968/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13960/ : FAILURE in 20m 11s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11976/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13966/ : FAILURE in 4m 05s

**Review by ivanmjartan — APPROVED** [review]

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.4190s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|136.0400s|
|✅|**dateFilter.spec.ts**|9|-|12.4260s|
|✅|**barChartDrilling.spec.ts**|4|-|6.0210s|
|✅|**attributeFilter.spec.ts**|1|-|7.5780s|
|✅|**dashboardDateRelated.spec.ts**|8|-|59.3930s|
|✅|**dashboard.spec.ts**|9|-|55.6590s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.2560s|
|✅|**dashboardKPI.spec.ts**|8|-|132.3770s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.3310s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.1280s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.7930s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.8040s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.0550s|
|✅|**attributeFilterButton.spec.ts**|13|-|49.3640s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.8570s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.3300s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.3580s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.1020s|
|✅|**dashboardDnD.spec.ts**|7|-|55.7420s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0790s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/447/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.4190s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|136.0400s|
|✅|**dateFilter.spec.ts**|9|-|12.4260s|
|✅|**barChartDrilling.spec.ts**|4|-|6.0210s|
|✅|**attributeFilter.spec.ts**|1|-|7.5780s|
|✅|**dashboardDateRelated.spec.ts**|8|-|59.3930s|
|✅|**dashboard.spec.ts**|9|-|55.6590s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.2560s|
|✅|**dashboardKPI.spec.ts**|8|-|132.3770s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.3310s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.1280s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.7930s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.8040s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.0550s|
|✅|**attributeFilterButton.spec.ts**|13|-|49.3640s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.8570s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.3300s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.3580s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.1020s|
|✅|**dashboardDnD.spec.ts**|7|-|55.7420s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0790s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/447/).

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3538

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/73/ : FAILURE in 5m 30s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/404/ : FAILURE in 1m 36s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13974/ : SUCCESS in 19m 00s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3677/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2520/ : SUCCESS in 11m 13s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/448/ : FAILURE in 24m 13s (non-voting)

**Pull request merged**
