### PR TITLE
BUGFIX: TNT-1394 remove blank spaces

### PR DESCRIPTION
**Pull request by NestorEncinas**
JIRA: TNT-1394

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11846/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13880/ : SUCCESS in 10m 09s

**Comment by NestorEncinas** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.5990s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.7660s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1300s|
|✅|**dashboardDnD.spec.ts**|7|-|54.8060s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.7490s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.9060s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.7280s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.1610s|
|✅|**barChartDrilling.spec.ts**|4|-|5.5280s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.9280s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.7690s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.6610s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.9230s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8720s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.9020s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.0370s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.6610s|
|✅|**dashboard.spec.ts**|9|-|56.3660s|
|✅|**dashboardKPI.spec.ts**|8|-|133.9890s|
|✅|**dateFilter.spec.ts**|9|-|11.7020s|
|✅|**attributeFilter.spec.ts**|1|-|6.1080s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/419/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.5990s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.7660s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1300s|
|✅|**dashboardDnD.spec.ts**|7|-|54.8060s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.7490s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.9060s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.7280s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.1610s|
|✅|**barChartDrilling.spec.ts**|4|-|5.5280s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.9280s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.7690s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.6610s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.9230s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8720s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.9020s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.0370s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.6610s|
|✅|**dashboard.spec.ts**|9|-|56.3660s|
|✅|**dashboardKPI.spec.ts**|8|-|133.9890s|
|✅|**dateFilter.spec.ts**|9|-|11.7020s|
|✅|**attributeFilter.spec.ts**|1|-|6.1080s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/419/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11847/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/123/ : SUCCESS in 21m 17s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3532

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/387/ : FAILURE in 1m 31s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3660/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2503/ : SUCCESS in 11m 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13884/ : SUCCESS in 10m 07s

**Pull request merged**
