### PR TITLE
FEATURE: RAIL-2460 - Live examples deployment fixes & tweaks

### PR DESCRIPTION
**Pull request by lupko**
Several smaller things:

-  Nginx config, deploy scripts had few small config bugs
   -  mapbox token propagation
   -  dockerized heroku run into issues with file permissions during login
   -  nginx config was not good, real backends (staging etc) would reject requests with 403

-  When examples in anonymous access, the details about the backend that normally show on the top are not there. 
-  Added route filtering based on build type. Some routes will not be included in 'public' build, only in 'stg3' build -> ranking filter
-  Modified links to point to v8 repo
-  Deleted the unneeded `server` code

---

Supported PR commands:

| Command         | Description            |
| --------------- | ---------------------- |
| `ok to test`    | Re-run standard checks |
| `extended test` | BackstopJS tests       |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/363/ : FAILURE in 3m 30s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/619/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2514/ : SUCCESS in 12m 18s

**Pull request merged**
