### PR TITLE
do not merge 

### PR DESCRIPTION
**Pull request by NghiLamGD**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by NghiLamGD** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10967/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13058/ : FAILURE in 8m 56s

**Comment by NghiLamGD** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10969/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13059/ : SUCCESS in 8m 56s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizing.spec.ts**|1|-|4.6590s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.4990s|
|✅|**dashboard.spec.ts**|9|-|56.8540s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.1400s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.2110s|
|✅|**dashboardFiltering.spec.ts**|3(2 skipped)|-|12.9900s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.9480s|
|✅|**dateFilter.spec.ts**|9|-|13.9490s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.7250s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.9160s|
|✅|**attributeFilterButton.spec.ts**|9|-|29.5240s|
|✅|**barChartDrilling.spec.ts**|4|-|6.3910s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.6640s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.8230s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.8560s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/356/).

**Pull request closed without merging**
