### PR TITLE
test

### PR DESCRIPTION
**Pull request by NestorEncinas**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by NestorEncinas** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9008/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10852/ : SUCCESS in 8m 31s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**barChartDrilling.spec.ts**|4|-|11.7220s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|12.1930s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|16.4960s|
|✅|**attributeFilterButton.spec.ts**|9|-|40.3270s|
|✅|**pivotTableSizing.spec.ts**|1|-|15.1770s|
|✅|**dashboardFiltering.spec.ts**|2|-|28.6560s|
|✅|**dashboard.spec.ts**|9|-|58.9760s|
|✅|**attributeFilterConfig.spec.ts**|3|-|32.7140s|
|✅|**drilling.spec.ts**|2|-|23.0110s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|20.9580s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|24.9680s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|18.2780s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.4370s|
|✅|**headlineChartDrilling.spec.ts**|2|-|10.4980s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|25.8380s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|52.7960s|
|❌|**[🎥 dateFilter.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/264/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">1</span>|23.0750s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/264/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9009/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/264/ : UNSTABLE in 17m 20s

**Pull request closed without merging**
