### PR TITLE
RELATED: SPACE-1664 - Update package licenses

### PR DESCRIPTION
**Pull request by lupko**
Update package licenses

-  All NPM packages _except_ sdk-ui-charts, sdk-ui-ext, sdk-ui-tests and sdk-ui-all is now under MIT
-  The sdk-ui-charts, sdk-ui-ext, sdk-ui-tests and sdk-ui-all have the GD EULA (updated to latest)
-  The live examples app also has GD EULA - even if the live examples are not actually packaged and published to NPM (they are app deployed to heroku)
-  The license in top-level directory is also the GD commercial EULA (updated to latest)
-  Readmes updated. Top level readme mentions the different package licenses

JIRA: SPACE-1664

---

Supported PR commands:

| Command         | Description            |
| --------------- | ---------------------- |
| `ok to test`    | Re-run standard checks |
| `extended test` | BackstopJS tests       |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Review by no23reason — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/321/ : FAILURE in 14m 22s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/577/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/2327/ : SUCCESS in 15m 21s

**Pull request merged**
