### PR TITLE
Tiger client - update OpenAPI schemas and regenerate client

### PR DESCRIPTION
**Pull request by lachtan**
There is a manual change in the metadata JSON to avoid `_1` naming of methods (relates to duplication of methods between organization-controller and organization-model-controller) plus fixing `typeGuards.js`.

### CODE REVIEW

**Comment by no23reason** [comment]
Will this manual change "survive" if we run the client generation again?

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/2823/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/4447/ : FAILURE in 3m 30s

**Comment by lachtan** [comment]
> Will this manual change "survive" if we run the client generation again?

Unfortunately no. It's fix for current situation in Tiger only when generating OpenAPI specs doesn't work satisfactory. We work on it and soon it will work without fixing JSON.

**Comment by no23reason** [comment]
Hm, that is concerning :-/ what if there are some new features added to the backend before you can fix this issue? Then we would re-introduce it, right? Do you have ETA for the backend fix to this, please?

**Comment by no23reason** [comment]
Closing in favor of #1133

**Pull request closed without merging**
