### PR TITLE
RELATED: RAIL-4862 fix nvmrc version

### PR DESCRIPTION
**Pull request by ivanmjartan**
JIRA: RAIL-4862

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3607

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.1750s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|53.7050s|
|✅|**dashboardDnD.spec.ts**|7|-|85.9450s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.7070s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.1080s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.7440s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.5980s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|226.2390s|
|✅|**barChartDrilling.spec.ts**|4|-|6.2520s|
|✅|**dashboardDateRelated.spec.ts**|8|-|73.8910s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.9370s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|20.7290s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.4810s|
|✅|**dateFilter.spec.ts**|9|-|14.8320s|
|✅|**dashboard.spec.ts**|9|-|60.5710s|
|✅|**attributeFilter.spec.ts**|1|-|12.6370s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|111.8820s|
|✅|**dashboardKPI.spec.ts**|8|-|223.1430s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.8410s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|8.4380s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.1420s|
|✅|**attributeFilterButton.spec.ts**|13|-|60.0490s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/506/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/120/ : FAILURE in 7m 12s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/447/ : FAILURE in 1m 45s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14202/ : SUCCESS in 24m 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3720/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2564/ : SUCCESS in 10m 42s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/506/ : SUCCESS in 28m 36s (non-voting)

**Pull request merged**
