### PR TITLE
feat: support localIdentifier on filters

### PR DESCRIPTION
**Pull request by hackerstanislav**
JIRA: F1-844

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Review by scavnickyj — APPROVED** [review]

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/212/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|16.850s|
|✅|**dashboardBasicActions.spec.ts**|2|-|15.395s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|14.019s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|8.446s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|28.791s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|8.987s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|110.162s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|26.363s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|14.175s|
|✅|**hideFilters.spec.ts**|20|-|137.162s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|35.910s|
|✅|**multipleDateFilters.spec.ts**|5|-|34.334s|
|✅|**unknownVisualization.spec.ts**|1|-|6.853s|
|✅|**manyData.spec.ts**|2|-|13.778s|
|✅|**scatterPlot.spec.ts**|2|-|8.766s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/212/).

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/213/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|14.880s|
|✅|**dashboardBasicActions.spec.ts**|2|-|14.867s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|12.884s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|7.900s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|25.801s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|8.391s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|102.921s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|25.981s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|13.330s|
|✅|**hideFilters.spec.ts**|20|-|132.838s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|35.565s|
|✅|**multipleDateFilters.spec.ts**|5|-|36.055s|
|✅|**unknownVisualization.spec.ts**|1|-|5.729s|
|✅|**manyData.spec.ts**|2|-|11.909s|
|✅|**scatterPlot.spec.ts**|2|-|8.546s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/213/).

**Review by pbenes — APPROVED** [review]

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - record

**Review by kandl — DISMISSED** [review]
LGTM

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/214/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|19.270s|
|✅|**dashboardBasicActions.spec.ts**|2|-|18.047s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|14.629s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|13.096s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|33.069s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|8.435s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|118.390s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|25.411s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|14.038s|
|✅|**hideFilters.spec.ts**|20|-|139.553s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|40.011s|
|✅|**multipleDateFilters.spec.ts**|5|-|35.736s|
|✅|**unknownVisualization.spec.ts**|1|-|5.655s|
|✅|**manyData.spec.ts**|2|-|11.729s|
|✅|**scatterPlot.spec.ts**|2|-|9.088s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/214/).

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/215/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|32.501s|
|✅|**dashboardBasicActions.spec.ts**|2|-|16.178s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|13.811s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|9.175s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|25.775s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|9.982s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|121.069s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|28.962s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|15.640s|
|✅|**hideFilters.spec.ts**|20|-|188.287s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|53.415s|
|✅|**multipleDateFilters.spec.ts**|5|-|39.582s|
|✅|**unknownVisualization.spec.ts**|1|-|6.223s|
|✅|**manyData.spec.ts**|2|-|12.299s|
|✅|**scatterPlot.spec.ts**|2|-|10.014s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/215/).

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/216/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|15.714s|
|✅|**dashboardBasicActions.spec.ts**|2|-|14.300s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|14.250s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|9.186s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|25.829s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|8.549s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|103.538s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|26.482s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|16.570s|
|✅|**hideFilters.spec.ts**|20|-|135.799s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|36.449s|
|✅|**multipleDateFilters.spec.ts**|5|-|34.453s|
|✅|**unknownVisualization.spec.ts**|1|-|6.493s|
|✅|**manyData.spec.ts**|2|-|15.683s|
|✅|**scatterPlot.spec.ts**|2|-|10.284s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/216/).

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - isolated

**Comment by hackerstanislav** [comment]
extended test - tiger-cypress - isolated

**Review by pbenes — APPROVED** [review]

**Pull request merged**
