### PR TITLE
FEATURE: TNT-687 Remove `enableAdFloatingDateRangeFilter`

### PR DESCRIPTION
**Pull request by NestorEncinas**
JIRA: TNT-687

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1908/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10611/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1908/ : SUCCESS in 34m 27s

**Comment by NestorEncinas** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.6920s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.8170s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|38.2180s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.4540s|
|✅|**dashboard.spec.ts**|9|-|52.1560s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.7650s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.7960s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.5840s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.6320s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.6070s|
|✅|**barChartDrilling.spec.ts**|4|-|6.3950s|
|✅|**dateFilter.spec.ts**|9|-|13.9660s|
|✅|**attributeFilterButton.spec.ts**|9|-|29.8220s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.9300s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/326/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10614/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/326/ : SUCCESS in 13m 54s

**Comment by NestorEncinas** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/62/ : UNSTABLE in 18m 00s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10617/ : SUCCESS in 11s

**Review by xMort — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/117/ : FAILURE in 2m 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3383/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2232/ : SUCCESS in 19m 45s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12697/ : SUCCESS in 19m 39s

**Pull request merged**
