### PR TITLE
BUGFIX: SD-2643 - update the default state for the Embed Insight Dialog

### PR DESCRIPTION
**Pull request by vannguyengd**
fix: default state for Embed Insight Dialog
JIRA: SD-2643

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Review by anvuong119 — APPROVED** [review]

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|24.4120s|
|✅|**dragDropAndMoveWidget.spec.ts**|3(1 skipped)|-|41.0840s|
|✅|**insightOnDashboard.spec.ts**|6(1 skipped)|-|42.0040s|
|✅|**dashboardBasicActions.spec.ts**|2|-|14.9230s|
|✅|**headerSection.spec.ts**|4(1 skipped)|-|61.0960s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/103/).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3591

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.2300s|
|✅|**dashboardDnD.spec.ts**|7|-|84.6570s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|111.2430s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.0750s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.3140s|
|✅|**dashboard.spec.ts**|9|-|60.2490s|
|✅|**attributeFilterButton.spec.ts**|13|-|48.0430s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.3830s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.2300s|
|✅|**dashboardDateRelated.spec.ts**|8|-|75.0310s|
|✅|**dashboardKPI.spec.ts**|8|-|159.5070s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|12.3660s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.0610s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|8.0560s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.1420s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0940s|
|✅|**barChartDrilling.spec.ts**|4|-|5.8080s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.2750s|
|✅|**attributeFilter.spec.ts**|1|-|6.2520s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|202.4070s|
|✅|**dateFilter.spec.ts**|9|-|12.4100s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.3310s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.4760s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/486/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/103/ : SUCCESS in 7m 56s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/431/ : FAILURE in 1m 41s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14113/ : SUCCESS in 17m 37s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3704/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2548/ : SUCCESS in 11m 00s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/486/ : SUCCESS in 24m 05s (non-voting)

**Pull request merged**
