### PR TITLE
Initialize total labels when getting reference point

### PR DESCRIPTION
**Pull request by pbenes**
JIRA: TNT-899

Do not fill data labels and total labels config in constructor as there are configurations which we are unable to decide at that moment (stackBy presence). Do this in getExtendedReferencePoint() instead.
Also add empty space only if the total labels are really visible (keeping the condition that ff must be on)

Touching screenshots which did not have dataLabels defined, when re-generated, they are going towards their original labels display before https://github.com/gooddata/gooddata-ui-sdk/pull/2726/files

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by pbenes** [comment]
extended test

**Comment by pbenes** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8907/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10758/ : SUCCESS in 12m 57s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|22.7590s|
|✅|**attributeFilterConfig.spec.ts**|3|-|31.0530s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|11.2810s|
|✅|**barChartDrilling.spec.ts**|4|-|10.4700s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|11.1350s|
|✅|**attributeFilterButton.spec.ts**|9|-|34.9360s|
|✅|**headlineChartDrilling.spec.ts**|2|-|8.1330s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|18.6160s|
|✅|**drilling.spec.ts**|2|-|20.1620s|
|✅|**dashboardFiltering.spec.ts**|2|-|24.4630s|
|✅|**pivotTableSizing.spec.ts**|1|-|8.8800s|
|✅|**dashboard.spec.ts**|9|-|53.2630s|
|✅|**dateFilter.spec.ts**|9|-|17.5770s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|42.1830s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.0730s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|10.8580s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|23.8050s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/256/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8909/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/256/ : SUCCESS in 14m 00s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1729/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8908/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1729/ : UNSTABLE in 27m 02s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8917/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10763/ : FAILURE in 17m 51s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8918/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10765/ : FAILURE in 17m 37s

**Comment by pbenes** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8919/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10766/ : FAILURE in 17m 32s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8920/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1732/ : UNSTABLE in 26m 57s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by pbenes** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8924/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10769/ : FAILURE in 18m 02s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1733/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8925/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1733/ : UNSTABLE in 28m 18s

**Comment by pbenes** [comment]
extended test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8938/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10777/ : FAILURE in 18m 00s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1736/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8939/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1736/ : SUCCESS in 25m 49s

**Comment by pbenes** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8941/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10779/ : SUCCESS in 21m 18s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1737/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8942/ : SUCCESS in 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1737/ : SUCCESS in 35m 30s

**Comment by pbenes** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8952/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10790/ : SUCCESS in 20m 47s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardFiltering.spec.ts**|2|-|28.0220s|
|✅|**drilling.spec.ts**|2|-|28.0440s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|18.8560s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|17.7040s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|35.4610s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|17.4110s|
|✅|**attributeFilterButton.spec.ts**|9|-|46.8390s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|42.3750s|
|✅|**dashboard.spec.ts**|9|-|64.1260s|
|✅|**attributeFilterConfig.spec.ts**|3|-|40.3710s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|17.6820s|
|✅|**dateFilter.spec.ts**|9|-|29.3220s|
|✅|**barChartDrilling.spec.ts**|4|-|17.5830s|
|✅|**pivotTableSizing.spec.ts**|1|-|15.1410s|
|✅|**headlineChartDrilling.spec.ts**|2|-|13.3930s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|25.6140s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|30.0890s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/260/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8953/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/260/ : SUCCESS in 19m 19s

**Comment by scavnickyj** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2783

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2557/ : SUCCESS in 1m 18s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2856/ : SUCCESS in 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1687/ : SUCCESS in 16m 40s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10797/ : SUCCESS in 17m 45s

**Pull request merged**
