### PR TITLE
RELATED: FET-1054 Enzyme to RTL (colorDropdown and Kpi)

### PR DESCRIPTION
**Pull request by marmil-cz**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by marmil-cz** [comment]
extended test

**Comment by marmil-cz** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9162/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10995/ : FAILURE in 22m 58s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizingReset.spec.ts**|15|-|42.7420s|
|✅|**drilling.spec.ts**|2|-|28.1330s|
|✅|**barChartDrilling.spec.ts**|4|-|18.2060s|
|❌|**[🎥 dateFilter.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/269/artifact/libs/sdk-ui-tests-e2e/cypress/videos/)**|9|<span style="color: red">1</span>|30.6160s|
|✅|**headlineChartDrilling.spec.ts**|2|-|14.0940s|
|✅|**dashboard.spec.ts**|9|-|61.7630s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|19.8990s|
|✅|**pivotTableSizing.spec.ts**|1|-|16.2270s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|30.7300s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|18.3570s|
|✅|**attributeFilterConfig.spec.ts**|3|-|41.0990s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|27.5770s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|18.4870s|
|✅|**attributeFilterButton.spec.ts**|9|-|47.3470s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|34.8370s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|18.2080s|
|✅|**dashboardFiltering.spec.ts**|2|-|37.1680s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/269/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9164/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/269/ : UNSTABLE in 20m 51s

**Comment by gdgate** [comment]
Build in pipeline check-extended aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by marmil-cz** [comment]
extended test

**Comment by marmil-cz** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboard.spec.ts**|9|-|54.4770s|
|✅|**attributeFilterConfig.spec.ts**|3|-|32.5540s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.2580s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|13.1130s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|18.8840s|
|✅|**dateFilter.spec.ts**|9|-|18.9850s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|46.8100s|
|✅|**pivotTableSizing.spec.ts**|1|-|10.0340s|
|✅|**dashboardFiltering.spec.ts**|2|-|25.1360s|
|✅|**barChartDrilling.spec.ts**|4|-|11.2850s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.8540s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|24.0930s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|25.5790s|
|✅|**drilling.spec.ts**|2|-|21.5310s|
|✅|**headlineChartDrilling.spec.ts**|2|-|8.6630s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.4140s|
|✅|**attributeFilterButton.spec.ts**|9|-|35.5420s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/270/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9172/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/270/ : SUCCESS in 15m 02s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9170/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11002/ : FAILURE in 19m 45s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1780/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9171/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1780/ : SUCCESS in 26m 52s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9173/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11003/ : SUCCESS in 22m 10s

**Review by xMort — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2829

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2604/ : FAILURE in 3m 34s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2903/ : SUCCESS in 32s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1735/ : SUCCESS in 17m 01s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11007/ : SUCCESS in 19m 48s

**Pull request merged**
