### PR TITLE
RELATED: RAIL-4791 Fix e2e recordings 

### PR DESCRIPTION
**Pull request by ivanmjartan**
---

Supported PR commands:

| Command                                               | Description                                                |
| ----------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                          | Re-run standard checks                                     |
| `extended check sonar`                                | SonarQube tests                                            |
| `extended check plugins`                              | Dashboard plugins tests                                    |
| `extended test - backstop`                            | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                |                                                            |
| `extended test - tiger-cypress - isolated <testName>` | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`   | Create a new recording for isolated Tiger tests.           |
| **E2E Cypress tests commands - BEAR**                 |                                                            |
| `extended test - cypress - isolated <testName>`       | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`         | Create a new recording for isolated Bear tests.            |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by ivanmjartan** [comment]
extended test - tiger-cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|❌|**[🎥 dashboardTiger.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-docker/19//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardTiger.spec.ts.mp4)**|9(4 skipped)|<span style="color: red">5</span>|154.3730s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-docker/19/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/71/ : FAILURE in 14m 23s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11230/ : SUCCESS in 8s

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul-docker/18/artifact/*zip*/archive.zip

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/72/ : FAILURE in 7m 12s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11231/ : SUCCESS in 13s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|25.0430s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-docker/20/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/73/ : SUCCESS in 6m 33s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11233/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11232/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13336/ : SUCCESS in 8m 21s

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|13.9160s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.7410s|
|✅|**dashboardDnD.spec.ts**|7|-|60.0670s|
|✅|**dashboardDependentFilter.spec.ts**|4|-|50.4470s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.5210s|
|✅|**dashboardKPI.spec.ts**|8|-|149.1750s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|151.2930s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.0380s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.7010s|
|✅|**dashboardDateRelated.spec.ts**|8|-|67.4020s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.3190s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|40.3820s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.3600s|
|✅|**attributeFilterButton.spec.ts**|9|-|30.3290s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.7230s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|38.7500s|
|✅|**barChartDrilling.spec.ts**|4|-|6.3220s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.4750s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.1290s|
|✅|**dashboard.spec.ts**|9|-|57.8690s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/370/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|13.9160s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.7410s|
|✅|**dashboardDnD.spec.ts**|7|-|60.0670s|
|✅|**dashboardDependentFilter.spec.ts**|4|-|50.4470s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.5210s|
|✅|**dashboardKPI.spec.ts**|8|-|149.1750s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|151.2930s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.0380s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.7010s|
|✅|**dashboardDateRelated.spec.ts**|8|-|67.4020s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.3190s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|40.3820s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.3600s|
|✅|**attributeFilterButton.spec.ts**|9|-|30.3290s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.7230s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|38.7500s|
|✅|**barChartDrilling.spec.ts**|4|-|6.3220s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.4750s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.1290s|
|✅|**dashboard.spec.ts**|9|-|57.8690s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/370/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/74/ : SUCCESS in 21m 51s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11234/ : SUCCESS in 6s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11235/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13337/ : SUCCESS in 8m 34s

**Review by hackerstanislav — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3423

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/284/ : FAILURE in 2m 45s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3551/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2399/ : SUCCESS in 16m 13s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13341/ : SUCCESS in 10m 24s

**Pull request merged**
