### PR TITLE
jsc test

### PR DESCRIPTION
**Pull request by scavnickyj**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11930/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13942/ : SUCCESS in 6m 46s

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated insightOnDashboard

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11932/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/149/ : SUCCESS in 17m 11s

**Comment by scavnickyj** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 😢 Some tests are failing. Consider fixing them.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.7740s|
|✅|**dashboard.spec.ts**|9|-|55.4250s|
|❌|**[🎥 dashboardKPI.spec.ts](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/438//artifact/libs/sdk-ui-tests-e2e/cypress/videos/dashboardKPI.spec.ts.mp4)**|8|<span style="color: red">1</span>|163.4800s|
|✅|**pivotTableSizing.spec.ts**|1|-|6.0070s|
|✅|**dashboardDateRelated.spec.ts**|8|-|60.4750s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|137.3470s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7850s|
|✅|**attributeFilter.spec.ts**|1|-|6.9490s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.2360s|
|✅|**dashboardDnD.spec.ts**|7|-|54.2760s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|9.1020s|
|✅|**attributeFilterButton.spec.ts**|13|-|46.9950s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0860s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.8840s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.3190s|
|✅|**barChartDrilling.spec.ts**|4|-|5.8620s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.3120s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|38.7990s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6090s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.4530s|
|✅|**dateFilter.spec.ts**|9|-|12.1110s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/438/).

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11937/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/150/ : FAILURE in 23m 35s

**Comment by scavnickyj** [comment]
extended test - cypress - isolated dashboardKPI

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11939/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/151/ : SUCCESS in 20m 23s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11959/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13957/ : SUCCESS in 6m 55s

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11964/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/155/ : FAILURE in 10m 25s

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated insightOnDashboard

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated insightOnDashboard

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11965/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/156/ : SUCCESS in 23m 52s

**Comment by scavnickyj** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0850s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.9940s|
|✅|**dashboard.spec.ts**|9|-|56.2420s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.3230s|
|✅|**dashboardDnD.spec.ts**|7|-|55.8720s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7960s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.0900s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.4500s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.1280s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8820s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8720s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1750s|
|✅|**dateFilter.spec.ts**|9|-|11.8800s|
|✅|**attributeFilter.spec.ts**|1|-|6.2170s|
|✅|**barChartDrilling.spec.ts**|4|-|5.6490s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.9800s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6330s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.8650s|
|✅|**dashboardKPI.spec.ts**|8|-|131.4640s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.7240s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.0940s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/443/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.0850s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.9940s|
|✅|**dashboard.spec.ts**|9|-|56.2420s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.3230s|
|✅|**dashboardDnD.spec.ts**|7|-|55.8720s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7960s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.0900s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|139.4500s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.1280s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8820s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8720s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1750s|
|✅|**dateFilter.spec.ts**|9|-|11.8800s|
|✅|**attributeFilter.spec.ts**|1|-|6.2170s|
|✅|**barChartDrilling.spec.ts**|4|-|5.6490s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.9800s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6330s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.8650s|
|✅|**dashboardKPI.spec.ts**|8|-|131.4640s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.7240s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.0940s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/443/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11967/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/157/ : SUCCESS in 21m 10s

**Pull request closed without merging**
