### PR TITLE
RELATED: RAIL-4483 Fix e2e tests

### PR DESCRIPTION
**Pull request by kandl**
- Use ECR docker images instead of harbor ones
- Refresh test recordings
- Skip tests, that cannot be updated due to unstable staging environment

JIRA: RAIL-4483

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by kandl** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9717/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11606/ : SUCCESS in 9m 11s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2(1 skipped)|-|9.8380s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|20.3650s|
|✅|**dashboardFiltering.spec.ts**|2|-|26.8830s|
|✅|**attributeFilterConfig.spec.ts**|3|-|33.7040s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.8440s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|13.1260s|
|✅|**headlineChartDrilling.spec.ts**|2|-|9.4200s|
|✅|**dateFilter.spec.ts**|9|-|21.2170s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.6410s|
|✅|**attributeFilterButton.spec.ts**|9(2 skipped)|-|30.7300s|
|✅|**barChartDrilling.spec.ts**|4|-|12.6090s|
|✅|**pivotTableSizing.spec.ts**|1|-|10.5010s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|24.5160s|
|✅|**dashboard.spec.ts**|9|-|55.4550s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|40.0800s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|25.9110s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/294/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9718/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/294/ : SUCCESS in 15m 27s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2965

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2758/ : FAILURE in 3m 12s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3061/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1901/ : SUCCESS in 23m 44s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11607/ : SUCCESS in 10m 02s

**Pull request merged**
