### PR TITLE
fix: e2e tests from pr improvements

### PR DESCRIPTION
**Pull request by pbenes**
JIRA: STL-935

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - isolated
extended test - record
```

### CODE REVIEW

**Comment by pbenes** [comment]
extended test - isolated

**Comment by pbenes** [comment]
extended test - isolated

**Comment by pbenes** [comment]
extended test - isolated

**Comment by pbenes** [comment]
extended test - isolated

**Comment by pbenes** [comment]
extended test - isolated

**Review by ivanmjartan — APPROVED** [review]

**Pull request merged**
