### PR TITLE
TRIVIAL: TNT-523 update localisations

### PR DESCRIPTION
**Pull request by NestorEncinas**
JIRA: TNT-523

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11895/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13919/ : SUCCESS in 14m 01s

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3544

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|14.1870s|
|✅|**dashboardKPI.spec.ts**|8|-|191.5240s|
|✅|**dashboardDnD.spec.ts**|7|-|79.3400s|
|✅|**dashboardDateRelated.spec.ts**|8|-|85.1100s|
|✅|**attributeFilter.spec.ts**|1|-|7.5230s|
|✅|**attributeFilterButton.spec.ts**|13|-|51.9930s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|42.2320s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|50.8970s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|193.7730s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.5200s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.9310s|
|✅|**barChartDrilling.spec.ts**|4|-|8.5620s|
|✅|**dashboard.spec.ts**|9|-|57.9510s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|8.3500s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.0500s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.2790s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.3070s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.7930s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.4800s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|108.3270s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.3520s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/425/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/51/ : FAILURE in 12m 29s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/393/ : FAILURE in 1m 49s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13921/ : SUCCESS in 23m 06s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3666/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2509/ : SUCCESS in 13m 06s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/425/ : SUCCESS in 29m 07s (non-voting)

**Pull request merged**
