### PR TITLE
FEATURE: TNT-1407 Single selection examples and tests

### PR DESCRIPTION
**Pull request by ivan-nejezchleb**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12031/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14011/ : SUCCESS in 11m 07s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record singleSelectionAttributeFilterparentChild

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12032/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/173/ : FAILURE in 5m 53s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12035/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14014/ : SUCCESS in 11m 09s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record singleSelectionAttributeFilterParentChild

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12037/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/174/ : FAILURE in 5m 44s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12036/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14015/ : SUCCESS in 11m 08s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record *

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12065/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14040/ : SUCCESS in 11m 13s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12079/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14052/ : SUCCESS in 11m 53s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record singleSelectionAttributeFilterParentChild

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12080/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/185/ : FAILURE in 5m 49s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record  singleSelectionAttributeFilterParentFilters

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12082/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/186/ : FAILURE in 5m 52s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12081/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14054/ : SUCCESS in 11m 06s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record dateFilter

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12083/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/187/ : FAILURE in 5m 41s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record singleSelectionAttributeFilterParentChild.spec.ts

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-record-zuul/24/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/BEAR/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|14.1970s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-record-zuul/24/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12085/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/188/ : SUCCESS in 6m 06s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12084/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14055/ : SUCCESS in 11m 02s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record singleSelectionAttributeFilterButton.spec.ts

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12086/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/189/ : FAILURE in 10m 45s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - isolated singleSelectionAttributeFilterButton.spec.ts

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12088/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/190/ : FAILURE in 9m 47s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12089/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/191/ : FAILURE in 10m 47s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - record singleSelectionAttributeFilterButton.spec.ts

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|9.5920s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-record-zuul/27/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12091/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/192/ : SUCCESS in 5m 58s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12090/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14057/ : SUCCESS in 11m 10s

**Comment by ivan-nejezchleb** [comment]
extended test - cypress - isolated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12092/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14058/ : SUCCESS in 11m 24s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.7420s|
|✅|**dashboardKPI.spec.ts**|8|-|134.6000s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.1300s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.0950s|
|✅|**dateFilter.spec.ts**|9|-|11.8380s|
|✅|**barChartDrilling.spec.ts**|4|-|5.5710s|
|✅|**dashboardDnD.spec.ts**|7|-|56.3300s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.2080s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.5530s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.9700s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1300s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.9260s|
|✅|**attributeFilter.spec.ts**|1|-|5.7970s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|11.2080s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7250s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|138.5970s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.9700s|
|✅|**dashboard.spec.ts**|9|-|55.8550s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.6720s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.6300s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.9120s|
|✅|**dashboardDateRelated.spec.ts**|8|-|60.8870s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.9130s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/468/).

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headerSection.spec.ts**|4(1 skipped)|-|62.8030s|
|✅|**dashboardBasicActions.spec.ts**|2|-|16.0190s|
|✅|**insightOnDashboard.spec.ts**|6(1 skipped)|-|42.4590s|
|✅|**dragDropAndMoveWidget.spec.ts**|3(1 skipped)|-|42.7410s|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|24.6270s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/91/).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3565

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6920s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4480s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.3070s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.4790s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|141.9980s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|93.0380s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8520s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7550s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|10.8080s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.0980s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0730s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.9490s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.7510s|
|✅|**attributeFilter.spec.ts**|1|-|6.3870s|
|✅|**dashboardDnD.spec.ts**|7|-|58.4640s|
|✅|**dashboard.spec.ts**|9|-|58.9750s|
|✅|**dashboardDateRelated.spec.ts**|8|-|68.3790s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.6570s|
|✅|**dashboardKPI.spec.ts**|8|-|132.8750s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.9000s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.9240s|
|✅|**dateFilter.spec.ts**|9|-|11.8010s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.8980s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/470/).

**Pull request merged**
