### PR TITLE
FEATURE: TNT-1181 Set enableDateFormats FF to true by default

### PR DESCRIPTION
**Pull request by scavnickyj**
JIRA: TNT-1181

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by scavnickyj** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10552/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12567/ : SUCCESS in 10m 27s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1904/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10553/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1904/ : UNSTABLE in 27m 45s

**Comment by scavnickyj** [comment]
check-extended-cypress

**Comment by scavnickyj** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizingReset.spec.ts**|15|-|40.3460s|
|✅|**headlineChartDrilling.spec.ts**|2|-|4.2540s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|8.2250s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.1210s|
|✅|**dateFilter.spec.ts**|9|-|15.1240s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.7730s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|21.2340s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.3850s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.6400s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.5160s|
|✅|**barChartDrilling.spec.ts**|4|-|7.1710s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|15.9430s|
|✅|**dashboard.spec.ts**|9|-|54.5680s|
|✅|**attributeFilterButton.spec.ts**|9|-|30.3570s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/325/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10555/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/325/ : SUCCESS in 13m 38s

**Review by marmil-cz — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3204

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/81/ : FAILURE in 2m 09s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3347/ : SUCCESS in 30s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2196/ : SUCCESS in 15m 52s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12571/ : SUCCESS in 10m 29s

**Pull request merged**
