### PR TITLE
RELATED: TNT-990 sdk-backend-tiger: use requested label for elements request

### PR DESCRIPTION
**Pull request by pbenes**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by pbenes** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9329/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11163/ : SUCCESS in 10m 04s

**Comment by pbenes** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9330/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1795/ : FAILURE in 20m 23s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**barChartDrilling.spec.ts**|4|-|10.9870s|
|✅|**headlineChartDrilling.spec.ts**|2|-|8.3430s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.0890s|
|✅|**dashboard.spec.ts**|9|-|53.9660s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|42.6930s|
|✅|**attributeFilterConfig.spec.ts**|3|-|30.7900s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|11.3460s|
|✅|**pivotTableSizing.spec.ts**|1|-|9.2460s|
|✅|**dashboardFiltering.spec.ts**|2|-|24.8100s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|11.6270s|
|✅|**attributeFilterButton.spec.ts**|9|-|35.3620s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|22.4230s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|11.4140s|
|✅|**dateFilter.spec.ts**|9|-|18.8500s|
|✅|**drilling.spec.ts**|2|-|20.7270s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|24.1390s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.3530s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/281/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9331/ : SUCCESS in 11s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/281/ : SUCCESS in 13m 59s

**Comment by pbenes** [comment]
extended test

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1796/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9334/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1796/ : SUCCESS in 25m 09s

**Pull request closed without merging**
