### PR TITLE
RELATED: FET-1054 Remove enzyme from sdk-ui-geo

### PR DESCRIPTION
**Pull request by scavnickyj**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12027/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14005/ : SUCCESS in 15m 55s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3563

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.8640s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1840s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.8010s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6530s|
|✅|**dashboardDnD.spec.ts**|7|-|54.5800s|
|✅|**dashboardDateRelated.spec.ts**|8|-|62.8880s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.2440s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4670s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.7920s|
|✅|**dashboardKPI.spec.ts**|8|-|134.0590s|
|✅|**dateFilter.spec.ts**|9|-|11.5580s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.3570s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|138.7030s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.8790s|
|✅|**dashboard.spec.ts**|9|-|55.3090s|
|✅|**attributeFilter.spec.ts**|1|-|6.4050s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.9980s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8220s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.6440s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.1370s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.5440s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/457/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/80/ : FAILURE in 10m 13s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/410/ : FAILURE in 1m 46s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14007/ : SUCCESS in 16m 10s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3683/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2526/ : SUCCESS in 10m 54s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/457/ : SUCCESS in 20m 39s (non-voting)

**Pull request merged**
