### PR TITLE
RELATED: FET-1054 Remove enzyme from sdk-ui-filters

### PR DESCRIPTION
**Pull request by scavnickyj**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12123/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14087/ : SUCCESS in 16m 21s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3585

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.0860s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.2550s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|146.2000s|
|✅|**dateFilter.spec.ts**|9|-|12.9190s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.7530s|
|✅|**dashboard.spec.ts**|9|-|55.8010s|
|✅|**barChartDrilling.spec.ts**|4|-|5.6990s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.2420s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|89.6860s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|12.1760s|
|✅|**dashboardDnD.spec.ts**|7|-|56.1130s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.5910s|
|✅|**dashboardKPI.spec.ts**|8|-|139.7280s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.8500s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.0020s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.0140s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.1810s|
|✅|**attributeFilterButton.spec.ts**|13|-|48.6900s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.3790s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.1910s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.0740s|
|✅|**attributeFilter.spec.ts**|1|-|7.6930s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.4660s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/480/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/98/ : FAILURE in 7m 44s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/425/ : FAILURE in 1m 43s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14096/ : SUCCESS in 24m 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3698/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2542/ : SUCCESS in 11m 28s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/480/ : SUCCESS in 22m 54s (non-voting)

**Pull request merged**
