### PR TITLE
FEATURE: MPNT-192 Clean up FF enableMSSQLDataSource

### PR DESCRIPTION
**Pull request by thongdq**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10717/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12775/ : SUCCESS in 11m 06s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**attributeFilterButton.spec.ts**|9|-|29.1580s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.4800s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.5530s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.5530s|
|✅|**barChartDrilling.spec.ts**|4|-|6.3390s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.3110s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.4290s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.0830s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.8280s|
|✅|**dashboard.spec.ts**|9|-|50.2570s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.9110s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.6820s|
|✅|**dateFilter.spec.ts**|9|-|13.5810s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.1540s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/329/).

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3273

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/177/ : FAILURE in 1m 55s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3443/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2292/ : SUCCESS in 15m 55s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12885/ : SUCCESS in 10m 08s

**Pull request merged**
