### PR TITLE
FEATURE: RAIL-4836 Api call for check entities override

### PR DESCRIPTION
**Pull request by hackerstanislav**
JIRA: RAIL-4836

---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12134/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14093/ : FAILURE in 5m 38s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12135/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14094/ : FAILURE in 6m 30s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/12136/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14095/ : SUCCESS in 7m 41s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3587

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardKPI.spec.ts**|8|-|204.3890s|
|✅|**attributeFilterButton.spec.ts**|13|-|50.7880s|
|✅|**dateFilter.spec.ts**|9|-|13.4610s|
|✅|**dashboardDnD.spec.ts**|7|-|90.2210s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.4870s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|12.7380s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.5010s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.7030s|
|✅|**barChartDrilling.spec.ts**|4|-|6.1090s|
|✅|**dashboard.spec.ts**|9|-|59.9610s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.5210s|
|✅|**attributeFilter.spec.ts**|1|-|7.6800s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.3690s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.9500s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.1160s|
|✅|**dashboardDateRelated.spec.ts**|8|-|92.3060s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|37.9600s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|52.8640s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|8.2210s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|114.1960s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.8830s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.8250s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|210.9080s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/481/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/99/ : FAILURE in 5m 17s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/426/ : FAILURE in 1m 41s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14097/ : SUCCESS in 17m 41s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3699/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2543/ : SUCCESS in 14m 33s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/481/ : SUCCESS in 30m 47s (non-voting)

**Pull request merged**
