### PR TITLE
feat: ui support for scheduling pdf exports

### PR DESCRIPTION
**Pull request by kandl**
Add support for scheduling pdf exports in the dashboard component.
Refactor components to new model and methods.
Cleanup unnecessary bear-backend related logic.
Map updated scheduling functionality to proper feature flag.

risk: low
JIRA: F1-437

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Review by scavnickyj — DISMISSED** [review]

**Review by scavnickyj — APPROVED** [review]

**Review by scavnickyj — DISMISSED** [review]

**Comment by kandl** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/188/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|13.377s|
|✅|**dashboardBasicActions.spec.ts**|2|-|16.096s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|15.150s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|7.713s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|27.059s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|8.850s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|93.740s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|26.043s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|14.120s|
|✅|**hideFilters.spec.ts**|20|-|143.338s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|35.650s|
|✅|**multipleDateFilters.spec.ts**|5|-|33.004s|
|✅|**unknownVisualization.spec.ts**|1|-|4.912s|
|✅|**manyData.spec.ts**|2|-|11.044s|
|✅|**scatterPlot.spec.ts**|2|-|7.524s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/188/).

**Comment by kandl** [comment]
extended test - tiger-cypress - isolated

**Review by scavnickyj — APPROVED** [review]

**Pull request merged**
