### PR TITLE
DO-NOT-MERGE

### PR DESCRIPTION
**Pull request by caohhung**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by caohhung** [comment]
extended test - tiger-cypress - isolated

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11668/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/75/ : FAILURE in 10m 36s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11667/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13717/ : SUCCESS in 18m 15s

**Comment by caohhung** [comment]
extended test - cypress - isolated

**Comment by caohhung** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardDateRelated.spec.ts**|8|-|59.9550s|
|✅|**dashboard.spec.ts**|9|-|56.6060s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|35.6570s|
|✅|**dashboardDnD.spec.ts**|7|-|54.4140s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.8570s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0980s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.0180s|
|✅|**dateFilter.spec.ts**|9|-|11.6000s|
|✅|**barChartDrilling.spec.ts**|4|-|5.6450s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.1440s|
|✅|**dashboardKPI.spec.ts**|8|-|129.7980s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6670s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.5480s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.7890s|
|✅|**attributeFilterButton.spec.ts**|9|-|27.4990s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8120s|
|✅|**attributeFilter.spec.ts**|1|-|5.7650s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|38.1510s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|83.3650s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6550s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|136.5090s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/402/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardDateRelated.spec.ts**|8|-|59.9550s|
|✅|**dashboard.spec.ts**|9|-|56.6060s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|35.6570s|
|✅|**dashboardDnD.spec.ts**|7|-|54.4140s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.8570s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0980s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.0180s|
|✅|**dateFilter.spec.ts**|9|-|11.6000s|
|✅|**barChartDrilling.spec.ts**|4|-|5.6450s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.1440s|
|✅|**dashboardKPI.spec.ts**|8|-|129.7980s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6670s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.5480s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.7890s|
|✅|**attributeFilterButton.spec.ts**|9|-|27.4990s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8120s|
|✅|**attributeFilter.spec.ts**|1|-|5.7650s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|38.1510s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|83.3650s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6550s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|136.5090s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/402/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11673/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/79/ : SUCCESS in 21m 09s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11683/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13726/ : SUCCESS in 6m 47s

**Comment by helobinvn** [comment]
extended check sonar

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-check-extended-sonar-PR3512

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/15026/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/3065/ : SUCCESS in 9m 33s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/15685/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/17210/ : SUCCESS in 7m 12s

**Pull request closed without merging**
