### PR TITLE
BUGFIX: RAIL-4839 attributeFilter component revert user selection

### PR DESCRIPTION
**Pull request by hackerstanislav**
AttributeFilter component revert user selection
if selection is changed immediately after
initialisation.

JIRA: RAIL-4839

---

Supported PR commands:

| Command                                               | Description                                                |
| ----------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                          | Re-run standard checks                                     |
| `extended check sonar`                                | SonarQube tests                                            |
| `extended check plugins`                              | Dashboard plugins tests                                    |
| `extended test - backstop`                            | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                |                                                            |
| `extended test - tiger-cypress - isolated <testName>` | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`   | Create a new recording for isolated Tiger tests.           |
| **E2E Cypress tests commands - BEAR**                 |                                                            |
| `extended test - cypress - isolated <testName>`       | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`         | Create a new recording for isolated Bear tests.            |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11522/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13606/ : SUCCESS in 11m 19s

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|11.5900s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.2940s|
|✅|**attributeFilterButton.spec.ts**|9|-|27.5590s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8620s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|137.8150s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6430s|
|✅|**barChartDrilling.spec.ts**|4|-|5.3770s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.7340s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8600s|
|✅|**dashboardDnD.spec.ts**|7|-|54.4040s|
|✅|**dashboard.spec.ts**|9|-|55.7380s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.0190s|
|✅|**dashboardKPI.spec.ts**|8|-|129.4670s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0140s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.4110s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6560s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.0780s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.8330s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8460s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.8340s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/397/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|11.5900s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.2940s|
|✅|**attributeFilterButton.spec.ts**|9|-|27.5590s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.8620s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|137.8150s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6430s|
|✅|**barChartDrilling.spec.ts**|4|-|5.3770s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.7340s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8600s|
|✅|**dashboardDnD.spec.ts**|7|-|54.4040s|
|✅|**dashboard.spec.ts**|9|-|55.7380s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.0190s|
|✅|**dashboardKPI.spec.ts**|8|-|129.4670s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.0140s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.4110s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.6560s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.0780s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.8330s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8460s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.8340s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/397/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11524/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/19/ : SUCCESS in 20m 29s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3484

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/344/ : FAILURE in 1m 58s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3616/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2460/ : SUCCESS in 12m 58s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13608/ : SUCCESS in 11m 51s

**Pull request merged**
