### PR TITLE
RELATED: F1-645 user feedback in chat

### PR DESCRIPTION
**Pull request by andriichumak**
Added user feedback to the AI chat

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Comment by andriichumak** [comment]
extended test - backstop

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/2716/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by andriichumak** [comment]
extended test - backstop

**Review by xMort — APPROVED** [review]

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/2717/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Pull request merged**
