### PR TITLE
Fix selecting single day in date range picker

### PR DESCRIPTION
**Pull request by scavnickyj**
JIRA: TNT-1059

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by scavnickyj** [comment]
extended test

**Comment by scavnickyj** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9746/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11637/ : SUCCESS in 15m 46s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headlineChartDrilling.spec.ts**|2|-|10.5130s|
|✅|**pivotTableSizing.spec.ts**|1|-|9.7970s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|12.3150s|
|✅|**barChartDrilling.spec.ts**|4|-|12.5950s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.2130s|
|✅|**dateFilter.spec.ts**|9|-|33.0580s|
|✅|**attributeFilterButton.spec.ts**|9(2 skipped)|-|36.0590s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|11.8540s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|27.8440s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|27.9840s|
|✅|**dashboard.spec.ts**|9|-|58.4300s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|31.8750s|
|✅|**attributeFilterConfig.spec.ts**|3|-|45.5990s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|38.3740s|
|✅|**dashboardFiltering.spec.ts**|2|-|28.3250s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2(1 skipped)|-|15.5110s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/297/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9748/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/297/ : SUCCESS in 17m 04s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1819/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9747/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1819/ : SUCCESS in 26m 15s

**Review by ivan-nejezchleb — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2974

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Pull request merged**
