### PR TITLE
Do not merge, for testing

### PR DESCRIPTION
**Pull request by pbenes**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by pbenes** [comment]
extended check cypress

**Comment by pbenes** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/46/ : UNSTABLE in 12m 19s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9767/ : SUCCESS in 12s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableSizing.spec.ts**|1|-|10.4960s|
|✅|**attributeFilterConfig.spec.ts**|3|-|33.4670s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|26.4300s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|13.1920s|
|✅|**dateFilter.spec.ts**|9|-|21.2560s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2(1 skipped)|-|9.7200s|
|✅|**attributeFilterButton.spec.ts**|9(2 skipped)|-|30.6050s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|20.8110s|
|✅|**barChartDrilling.spec.ts**|4|-|12.5590s|
|✅|**dashboardFiltering.spec.ts**|2|-|28.8520s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.7190s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|24.5610s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|39.9770s|
|✅|**dashboard.spec.ts**|9|-|56.2560s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.8360s|
|✅|**headlineChartDrilling.spec.ts**|2|-|9.7640s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/300/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9766/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/300/ : SUCCESS in 14m 48s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9765/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11648/ : SUCCESS in 30m 48s

**Comment by pbenes** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10657/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12692/ : SUCCESS in 12m 33s

**Pull request closed without merging**
