### PR TITLE
CONFIG: RAIL-4644 Adopt cypress infra from KD

### PR DESCRIPTION
**Pull request by caohhung**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by caohhung** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10888/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12977/ : FAILURE in 14m 21s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headlineChartDrilling.spec.ts**|2|-|4.0360s|
|✅|**barChartDrilling.spec.ts**|4|-|7.9960s|
|✅|**attributeFilterButton.spec.ts**|9|-|35.5350s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|20.6990s|
|✅|**dateFilter.spec.ts**|9|-|29.7280s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.0620s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.7880s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.5820s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.2750s|
|✅|**dashboard.spec.ts**|9|-|62.9640s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|25.1390s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|21.5890s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.8050s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|12.4050s|

You can find full report [here](#).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10889/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/338/ : SUCCESS in 15m 51s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10890/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12978/ : SUCCESS in 22m 18s

**Comment by caohhung** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10892/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/339/ : FAILURE in 25s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by caohhung** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check-extended-cypress aborted.

**Comment by caohhung** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|27.6860s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|30.3070s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.8880s|
|✅|**barChartDrilling.spec.ts**|4|-|8.3280s|
|✅|**dashboard.spec.ts**|9|-|61.0910s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|12.0500s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|15.7150s|
|✅|**pivotTableSizing.spec.ts**|1|-|9.0620s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|11.5880s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.0400s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.9720s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|11.6240s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|54.8330s|
|✅|**attributeFilterButton.spec.ts**|9|-|32.2020s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/341/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10896/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/341/ : SUCCESS in 16m 22s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10895/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12981/ : SUCCESS in 23m 31s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10901/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12988/ : SUCCESS in 20m 22s

**Pull request closed without merging**
