### PR TITLE
feat: add support for cache id for attribute elements

### PR DESCRIPTION
**Pull request by no23reason**
This allows the clients to identify the result (that always contains all the elements) so that the paging returns consistent results.
It also prevents the underlying database from being queried excessively (which would lead to massive numbers of Quiver flights being created).

The intended e2e flow is as follows:
- On the first query for elements, the client sends an empty cacheId.
- The server will compute an appropriate value for the cacheId:
   - For datasources with caching enabled, the backend will calculate the cacheId based on the request
     (as it used to do before this was added).
     This means that different clients querying the same label will get the same cacheId, and can effectively reuse the Quiver cache.
   - For datasources with caching disabled, the backend will return a random string, so the client will get their own elements result, not reusing anything.
     Thanks to the datasource cache strategy, this will be placed in the temporary flight path with only a 15-minute TTL.
- For subsequent requests, the client should send the cacheId returned by the server for the first request.
  This will reuse the cache even for the datasources with cache disabled: it is reasonable to expect that we can cache data in one browser session (we already do that in fact with the caching backends).

JIRA: CQ-198

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
// Tiger platform
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

```
// Bear platform
extended test - cypress - integrated
extended test - cypress - isolated
extended test - cypress - record
```

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/18168/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/19759/ : FAILURE in 14m 07s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/18170/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/19764/ : SUCCESS in 11m 59s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR4722

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/3983/ : SUCCESS in 11m 39s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/19768/ : SUCCESS in 11m 51s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-pipeline/1641/ : SUCCESS in 11m 27s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/5152/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/1862/ : SUCCESS in 1m 26s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-pipeline/1651/ : SUCCESS in 14m 50s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-compatibility-pipeline/646/ : SUCCESS in 6m 05s

**Pull request merged**
