### PR TITLE
test: use predictable widget local identifiers for tests

### PR DESCRIPTION
**Pull request by scavnickyj**
JIRA: F1-523
risk: nonprod

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - record insightOnDashboard

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|37.642s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/196/).

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated insightOnDashboard

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|13.139s|
|✅|**dashboardBasicActions.spec.ts**|2|-|14.775s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|13.877s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|7.111s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|24.072s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|7.454s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|89.462s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|25.251s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|13.754s|
|✅|**hideFilters.spec.ts**|20|-|126.455s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|33.934s|
|✅|**multipleDateFilters.spec.ts**|5|-|33.889s|
|✅|**unknownVisualization.spec.ts**|1|-|4.682s|
|✅|**manyData.spec.ts**|2|-|12.361s|
|✅|**scatterPlot.spec.ts**|2|-|8.321s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/197/).

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - record insightOnDashboard

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/198/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|36.113s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/198/).

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated insightOnDashboard

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - record insightOnDashboard

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/199/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|52.949s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/199/).

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated insightOnDashboard

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - record

**Comment by scavnickyj** [comment]
Screenshot 2024-07-31 at 14 21 32

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/200/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|13.422s|
|✅|**dashboardBasicActions.spec.ts**|2|-|16.083s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|15.229s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|7.014s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|27.887s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|7.972s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|102.700s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|27.124s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|17.105s|
|✅|**hideFilters.spec.ts**|20|-|150.357s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|40.231s|
|✅|**multipleDateFilters.spec.ts**|5|-|38.595s|
|✅|**unknownVisualization.spec.ts**|1|-|8.791s|
|✅|**manyData.spec.ts**|2|-|19.511s|
|✅|**scatterPlot.spec.ts**|2|-|13.021s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/200/).

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - isolated

**Comment by scavnickyj** [comment]
extended test - tiger-cypress - integrated

**Review by kandl — APPROVED** [review]
LGTM

**Pull request merged**
