### PR TITLE
FEATURE: QA-22262 Move metrics from fixtures repo

### PR DESCRIPTION
**Pull request by NghiLamGD**
---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/18978/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/20760/ : SUCCESS in 4m 18s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by myhoai** [comment]
extended test - tiger-cypress - record

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/19003/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/20777/ : SUCCESS in 10m 15s

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/187/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|22.827s|
|✅|**dashboardBasicActions.spec.ts**|2|-|15.021s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|13.710s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|25.127s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|7.261s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|88.175s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|24.572s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|13.415s|
|✅|**hideFilters.spec.ts**|20|-|144.699s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|34.331s|
|✅|**multipleDateFilters.spec.ts**|5|-|33.061s|
|✅|**unknownVisualization.spec.ts**|1|-|5.078s|
|✅|**manyData.spec.ts**|2|-|10.810s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/187/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/19004/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/2176/ : SUCCESS in 12m 26s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/19008/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/20780/ : SUCCESS in 11m 32s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/5517/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/2219/ : SUCCESS in 1m 08s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul-pipeline/2021/ : SUCCESS in 11m 35s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/20788/ : SUCCESS in 10m 22s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-compatibility-pipeline/787/ : FAILURE in 4m 47s

**Pull request closed without merging**
