### PR TITLE
Configure Renovate

### PR DESCRIPTION
**Pull request by yenkins-admin**
Welcome to [Renovate](https://togithub.com/renovatebot/renovate)! This is an onboarding PR to help you understand and configure settings before regular Pull Requests begin.

🚦 To activate Renovate, merge this Pull Request. To disable Renovate, simply close this Pull Request unmerged.

---
### Detected Package Files

 * `libs/sdk-ui-tests-e2e/docker-compose-integrated.yaml` (docker-compose)
 * `libs/sdk-ui-tests-e2e/docker-compose-isolated.yaml` (docker-compose)
 * `libs/sdk-ui-tests-e2e/Dockerfile` (dockerfile)
 * `libs/sdk-ui-tests-e2e/Dockerfile_local` (dockerfile)
 * `libs/sdk-ui-web-components/Dockerfile` (dockerfile)
### Configuration

🔡 Renovate has detected a custom config for this PR. Feel free to ask for [help](https://togithub.com/renovatebot/renovate/discussions) if you have any doubts and would like it reviewed.

Important: Now that this branch is edited, Renovate can't rebase it from the base branch any more. If you make changes to the base branch that could impact this onboarding PR, please merge them manually.

### What to Expect

With your current configuration, Renovate will create 5 Pull Requests:

<details>
<summary>chore(deps): update 020413372491.dkr.ecr.us-east-1.amazonaws.com/3rdparty/nginxinc/nginx-unprivileged docker tag to v1.23.3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/020413372491.dkr.ecr.us-east-1.amazonaws.com-3rdparty-nginxinc-nginx-unprivileged-1.x`
  - Merge into: `master`
  - Upgrade 020413372491.dkr.ecr.us-east-1.amazonaws.com/3rdparty/nginxinc/nginx-unprivileged to `1.23.3-alpine`

</details>

<details>
<summary>chore(deps): update cypress/included docker tag to v10.11.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/cypress-included-10.x`
  - Merge into: `master`
  - Upgrade cypress/included to `10.11.0`

</details>

<details>
<summary>chore(deps): update nginxinc/nginx-unprivileged docker tag to v1.23.3</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/nginxinc-nginx-unprivileged-1.x`
  - Merge into: `master`
  - Upgrade nginxinc/nginx-unprivileged to `1.23.3`

</details>

<details>
<summary>chore(deps): update wiremock/wiremock docker tag to v2.35.0</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/wiremock-wiremock-2.x`
  - Merge into: `master`
  - Upgrade wiremock/wiremock to `2.35.0`

</details>

<details>
<summary>chore(deps): update cypress/included docker tag to v12</summary>

  - Schedule: ["at any time"]
  - Branch name: `renovate/cypress-included-12.x`
  - Merge into: `master`
  - Upgrade cypress/included to `12.8.1`

</details>

<br />

🚸 Branch creation will be limited to maximum 2 per hour, so it doesn't swamp any CI resources or overwhelm the project. See docs for `prhourlylimit` for details.

---

❓ Got questions? Check out Renovate's [Docs](https://docs.renovatebot.com/), particularly the Getting Started section.
If you need any further assistance then you can also [request help here](https://togithub.com/renovatebot/renovate/discussions).

---

This PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11569/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13644/ : SUCCESS in 20m 03s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11580/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13651/ : SUCCESS in 18m 07s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11646/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13704/ : SUCCESS in 16m 40s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11706/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13746/ : SUCCESS in 18m 18s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3493

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.0010s|
|✅|**singleSelectionAttributeFilterButton.spec.ts**|3|-|7.5790s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.8260s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8830s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.5830s|
|✅|**dashboardDnD.spec.ts**|7|-|56.4430s|
|✅|**singleSelectionAttributeFilterParentChild.spec.ts**|2|-|11.8760s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8840s|
|✅|**dashboardKPI.spec.ts**|8|-|134.2810s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.7650s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|37.2430s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4750s|
|✅|**attributeFilter.spec.ts**|1|-|6.1750s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|35.9080s|
|✅|**dashboard.spec.ts**|9|-|56.2230s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.2040s|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.8630s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|84.8670s|
|✅|**dashboardDateRelated.spec.ts**|8|-|61.5620s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1310s|
|✅|**dateFilter.spec.ts**|9|-|11.8430s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|136.9040s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.6360s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/474/).

**Pull request merged**
