### PR TITLE
RELATED: TNT-910 Align text to left in textarea of editableLabel

### PR DESCRIPTION
**Pull request by marmil-cz**
JIRA: TNT-910

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by marmil-cz** [comment]
extended test

**Comment by marmil-cz** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9135/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10962/ : SUCCESS in 16m 08s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|18.6650s|
|✅|**attributeFilterConfig.spec.ts**|3|-|31.2170s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|22.6820s|
|✅|**pivotTableSizing.spec.ts**|1|-|9.1210s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|11.4540s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|23.9020s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|11.5100s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|11.1380s|
|✅|**headlineChartDrilling.spec.ts**|2|-|8.2010s|
|✅|**dashboard.spec.ts**|9|-|53.4470s|
|✅|**attributeFilterButton.spec.ts**|9|-|35.0480s|
|✅|**dashboardFiltering.spec.ts**|2|-|25.6240s|
|✅|**drilling.spec.ts**|2|-|21.1850s|
|✅|**barChartDrilling.spec.ts**|4|-|10.8630s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|18.6030s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|11.1190s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|42.5960s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/268/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9138/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/268/ : SUCCESS in 13m 59s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1775/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9137/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1775/ : SUCCESS in 27m 54s

**Review by NestorEncinas — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2592/ : SUCCESS in 2m 11s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2891/ : SUCCESS in 29s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1723/ : SUCCESS in 16m 49s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10967/ : SUCCESS in 15m 46s

**Pull request merged**
