### PR TITLE
RELATED: FET-772 Remove IE-specific polyfills, upgrade blocked dependencies

### PR DESCRIPTION
**Pull request by ivanmjartan**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11889/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13913/ : SUCCESS in 20m 19s

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11897/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13923/ : SUCCESS in 17m 42s

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11898/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/136/ : ABORTED in 1h 00m 19s

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build in pipeline check-extended aborted.

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11909/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13929/ : SUCCESS in 16m 30s

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11910/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/139/ : SUCCESS in 20m 57s

**Comment by ivanmjartan** [comment]
extended test - tiger-cypress - isolated

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11912/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/140/ : FAILURE in 10m 39s

**Comment by ivanmjartan** [comment]
extended test - cypress - isolated

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11917/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13932/ : SUCCESS in 19m 28s

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.4190s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|38.6430s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.2100s|
|✅|**dashboardDateRelated.spec.ts**|8|-|70.7100s|
|✅|**barChartDrilling.spec.ts**|4|-|5.7880s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.4060s|
|✅|**attributeFilter.spec.ts**|1|-|7.5280s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.2630s|
|✅|**dashboardDnD.spec.ts**|7|-|62.5820s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.2470s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.8890s|
|✅|**attributeFilterButton.spec.ts**|13|-|49.5890s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.3010s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.2230s|
|✅|**dashboardKPI.spec.ts**|8|-|152.4180s|
|✅|**dashboard.spec.ts**|9|-|60.1940s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.8540s|
|✅|**dateFilter.spec.ts**|9|-|13.0320s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|154.9500s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|93.1340s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|38.3370s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/431/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.4190s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|38.6430s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.2100s|
|✅|**dashboardDateRelated.spec.ts**|8|-|70.7100s|
|✅|**barChartDrilling.spec.ts**|4|-|5.7880s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.4060s|
|✅|**attributeFilter.spec.ts**|1|-|7.5280s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.2630s|
|✅|**dashboardDnD.spec.ts**|7|-|62.5820s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.2470s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.8890s|
|✅|**attributeFilterButton.spec.ts**|13|-|49.5890s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.3010s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.2230s|
|✅|**dashboardKPI.spec.ts**|8|-|152.4180s|
|✅|**dashboard.spec.ts**|9|-|60.1940s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|18.8540s|
|✅|**dateFilter.spec.ts**|9|-|13.0320s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|154.9500s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|93.1340s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|38.3370s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/431/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11918/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/142/ : SUCCESS in 23m 47s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1983/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11921/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/143/ : SUCCESS in 22m 13s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11953/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13951/ : SUCCESS in 16m 13s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3542

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/66/ : FAILURE in 10m 08s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/399/ : FAILURE in 1m 40s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13952/ : SUCCESS in 22m 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3672/ : SUCCESS in 14s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2515/ : SUCCESS in 13m 23s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/441/ : FAILURE in 28m 36s (non-voting)

**Pull request merged**
