### PR TITLE
FEATURE: TNT-1284 update dashboard permissions from backend after permissions change

### PR DESCRIPTION
**Pull request by tomassatinsky**
JIRA: TNT-1284

---

Supported PR commands:

| Command                                               | Description                                                |
| ----------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                          | Re-run standard checks                                     |
| `extended check sonar`                                | SonarQube tests                                            |
| `extended check plugins`                              | Dashboard plugins tests                                    |
| `extended test - backstop`                            | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                |                                                            |
| `extended test - tiger-cypress - isolated <testName>` | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`   | Create a new recording for isolated Tiger tests.           |
| **E2E Cypress tests commands - BEAR**                 |                                                            |
| `extended test - cypress - isolated <testName>`       | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`         | Create a new recording for isolated Bear tests.            |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11348/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13420/ : SUCCESS in 13m 33s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11351/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13423/ : SUCCESS in 12m 53s

**Comment by tomassatinsky** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.8560s|
|✅|**dashboardDependentFilter.spec.ts**|4|-|47.6280s|
|✅|**barChartDrilling.spec.ts**|4|-|6.9400s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.0620s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.7120s|
|✅|**dashboardKPI.spec.ts**|8|-|144.3730s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.0670s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.6720s|
|✅|**attributeFilterButton.spec.ts**|9|-|30.4940s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.2940s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|40.8020s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.6530s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.5840s|
|✅|**dateFilter.spec.ts**|9|-|14.0820s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.9550s|
|✅|**dashboard.spec.ts**|9|-|58.8660s|
|✅|**dashboardDnD.spec.ts**|7|-|58.7600s|
|✅|**dashboardDateRelated.spec.ts**|8|-|67.7730s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|152.1380s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.8170s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/390/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.8560s|
|✅|**dashboardDependentFilter.spec.ts**|4|-|47.6280s|
|✅|**barChartDrilling.spec.ts**|4|-|6.9400s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.0620s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|13.7120s|
|✅|**dashboardKPI.spec.ts**|8|-|144.3730s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.0670s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.6720s|
|✅|**attributeFilterButton.spec.ts**|9|-|30.4940s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.2940s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|40.8020s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.6530s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.5840s|
|✅|**dateFilter.spec.ts**|9|-|14.0820s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.9550s|
|✅|**dashboard.spec.ts**|9|-|58.8660s|
|✅|**dashboardDnD.spec.ts**|7|-|58.7600s|
|✅|**dashboardDateRelated.spec.ts**|8|-|67.7730s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|152.1380s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.8170s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/390/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/125/ : SUCCESS in 22m 04s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11352/ : SUCCESS in 8s

**Review by ivanmjartan — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3439

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/301/ : FAILURE in 3m 25s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3568/ : SUCCESS in 21s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2416/ : SUCCESS in 16m 22s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13424/ : SUCCESS in 13m 29s

**Pull request merged**
