### PR TITLE
fix: avoid additional call for earlyAccess flags

### PR DESCRIPTION
**Pull request by kandl**
Organization earlyAccess flags can be get from the profile API, so avoid an additional call to the organization API to get the info.

risk: low
JIRA: F1-507

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Comment by kandl** [comment]
extended test - tiger-cypress - record

**Comment by kandl** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|12.760s|
|✅|**dashboardBasicActions.spec.ts**|2|-|15.018s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|14.392s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|7.198s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|25.235s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|7.434s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|89.400s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|24.762s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|15.120s|
|✅|**hideFilters.spec.ts**|20|-|132.813s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|36.533s|
|✅|**multipleDateFilters.spec.ts**|5|-|35.452s|
|✅|**unknownVisualization.spec.ts**|1|-|4.904s|
|✅|**manyData.spec.ts**|2|-|12.119s|
|✅|**scatterPlot.spec.ts**|2|-|8.166s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/193/).

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/194/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|13.457s|
|✅|**dashboardBasicActions.spec.ts**|2|-|15.979s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|14.779s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|7.184s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|26.143s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|7.751s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|92.800s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|26.631s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|14.517s|
|✅|**hideFilters.spec.ts**|20|-|136.141s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|37.118s|
|✅|**multipleDateFilters.spec.ts**|5|-|36.843s|
|✅|**unknownVisualization.spec.ts**|1|-|5.264s|
|✅|**manyData.spec.ts**|2|-|12.835s|
|✅|**scatterPlot.spec.ts**|2|-|8.742s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/194/).

**Review by scavnickyj — APPROVED** [review]

**Pull request merged**
