### PR TITLE
RELATED: RAIL-4158 first part of KPI config panel migration

### PR DESCRIPTION
**Pull request by no23reason**
Migrates most parts of the KPI config panel. This is not all, but to keep the PR reasonably small and to allow others to use the common components, I am cutting here.

### Things done

* migrated the Kpi config panel
* migrated the Metric dropdown
* migrated the filter configuration
* migrated the configuration messages (like "This KPI has X alerts, you will break them")
* fixed a nasty bug in `loadDateDatasetsForInsight` saga
* improved the way the widget selection is handled

### Things missing

* integration into the KPI edit mode (migrates only the components, the integration will be in a separate PR, I tested it locally with a hacky code)
* handling of close button click on ConfigurationBubble
* handling of drill to report (needs a bear specific function, will figure out the best pattern for that in a separate PR)
* some small TODOs and commented-out code in the migrated components (will be addressed in a separate PR with the integration)

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8775/ : SUCCESS in 9s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10616/ : SUCCESS in 11m 57s

**Comment by no23reason** [comment]
extended check cypress

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/8788/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/244/ : UNSTABLE in 13m 50s

**Review by hackerstanislav — APPROVED** [review]

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2515/ : SUCCESS in 1m 02s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/2814/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1639/ : SUCCESS in 20m 05s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/10637/ : SUCCESS in 10m 52s

**Pull request merged**
