### PR TITLE
Use localised date formats in DateFilter

### PR DESCRIPTION
**Pull request by scavnickyj**
JIRA: TNT-1108

---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by scavnickyj** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10358/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12352/ : SUCCESS in 24m 44s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1884/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10361/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1884/ : UNSTABLE in 27m 23s

**Comment by scavnickyj** [comment]
extended check cypress

**Comment by scavnickyj** [comment]
extended test

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|20.2110s|
|✅|**attributeFilterButton.spec.ts**|9|-|29.7910s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.8870s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.5190s|
|✅|**barChartDrilling.spec.ts**|4|-|6.9320s|
|✅|**dateFilter.spec.ts**|9|-|14.0630s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.4690s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.8960s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.2200s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|40.5580s|
|✅|**dashboard.spec.ts**|9|-|51.0550s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.6060s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.0780s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.0770s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/323/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10366/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/323/ : SUCCESS in 13m 08s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10365/ : SUCCESS in 10s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12358/ : SUCCESS in 21m 58s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1885/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10367/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1885/ : UNSTABLE in 34m 40s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10373/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12364/ : SUCCESS in 21m 40s

**Comment by scavnickyj** [comment]
extended test

**Comment by scavnickyj** [comment]
check-extended-cypress

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10379/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/12369/ : SUCCESS in 21m 26s

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1886/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10380/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1886/ : SUCCESS in 24m 52s

**Comment by scavnickyj** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dateFilter.spec.ts**|9|-|15.3130s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|6.5660s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|6.7630s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|14.5470s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|19.6820s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|6.8890s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|39.4010s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.8110s|
|✅|**dashboard.spec.ts**|9|-|50.6590s|
|✅|**pivotTableSizing.spec.ts**|1|-|4.4540s|
|✅|**attributeFilterButton.spec.ts**|9|-|30.7890s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.6340s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|16.8810s|
|✅|**barChartDrilling.spec.ts**|4|-|6.3480s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/324/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/10381/ : SUCCESS in 8s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/324/ : SUCCESS in 13m 38s

**Review by kandl — APPROVED** [review]
LGTM

**Pull request merged**
