### PR TITLE
BUGFIX: Update "Invite" Item style in header menu item

### PR DESCRIPTION
**Pull request by thuytran-gooddata**
---

Supported PR commands:

| Command                  | Description             |
| ------------------------ | ----------------------- |
| `ok to test`             | Re-run standard checks  |
| `extended test`          | BackstopJS tests        |
| `extended check sonar`   | SonarQube tests         |
| `extended check cypress` | Cypress E2E tests       |
| `extended check plugins` | Dashboard plugins tests |

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `check-extended` passes
-   [ ] `check-extended-cypress` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9743/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11636/ : SUCCESS in 15m 58s

**Comment by thuytran-gooddata** [comment]
extended test

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1818/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9744/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1818/ : SUCCESS in 27m 05s

**Comment by thuytran-gooddata** [comment]
extended check cypress

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|25.3640s|
|✅|**attributeFilterButton.spec.ts**|9(2 skipped)|-|29.0440s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|19.6750s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|23.5770s|
|✅|**pivotTableSizingReset.spec.ts**|15(2 skipped)|-|42.2700s|
|✅|**pivotTableSizing.spec.ts**|1|-|10.7090s|
|✅|**headlineChartDrilling.spec.ts**|2|-|9.0490s|
|✅|**barChartDrilling.spec.ts**|4|-|11.8860s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|12.4980s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2(1 skipped)|-|8.9200s|
|✅|**dateFilter.spec.ts**|9|-|19.9640s|
|✅|**attributeFilterConfig.spec.ts**|3|-|32.5020s|
|✅|**dashboardFiltering.spec.ts**|2|-|27.6490s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|13.5220s|
|✅|**dashboard.spec.ts**|9|-|54.2530s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|12.4400s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/296/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9745/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tests/296/ : SUCCESS in 13m 48s

**Comment by thuytran-gooddata** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/43/ : UNSTABLE in 12m 48s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9749/ : SUCCESS in 6s

**Comment by thuytran-gooddata** [comment]
extended check plugins

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-dashboard-plugin-tests/44/ : UNSTABLE in 14m 08s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9750/ : SUCCESS in 4s

**Comment by thuytran-gooddata** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9752/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11638/ : SUCCESS in 15m 57s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/9756/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11643/ : SUCCESS in 17m 50s

**Review by anvuong119 — APPROVED** [review]

**Comment by anvuong119** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2973

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build failed (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2768/ : SUCCESS in 1m 03s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3071/ : SUCCESS in 16s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1911/ : SUCCESS in 15m 42s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11664/ : FAILURE in 16m 03s

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR2973

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul-el7/2769/ : SUCCESS in 1m 03s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3072/ : SUCCESS in 15s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/1912/ : SUCCESS in 15m 40s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/11665/ : SUCCESS in 15m 37s

**Pull request merged**
