### PR TITLE
feat: fetch displayforms via selective api

### PR DESCRIPTION
**Pull request by pbenes**
avoid loading all attributes to fetch provided set of displayforms

risk: low
JIRA: STL-880

---

> [!IMPORTANT]
> Please, **don't forget to run `rush change`** for the commits that introduce **new features** 🙏

---

Refer to [documentation](https://github.com/gooddata/gooddata-ui-sdk/blob/master/dev_docs/continuous_integration.md) to see how to run checks and tests in the pull request. This is the list of the most used commands:

```
extended test - backstop
```

```
extended test - tiger-cypress - integrated
extended test - tiger-cypress - isolated
extended test - tiger-cypress - record
```

### CODE REVIEW

**Comment by pbenes** [comment]
extended test - tiger-cypress - isolated

**Comment by pbenes** [comment]
extended test - tiger-cypress - record

**Comment by yenkins** [comment]
**Cypress recording succeeded** :tada:

Here is your new recording: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/211/artifact/libs/sdk-ui-tests-e2e/recordings/mappings/TIGER/*zip*/archive.zip

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**crossFiltering.spec.ts**|1|-|14.557s|
|✅|**dashboardBasicActions.spec.ts**|2|-|14.740s|
|✅|**dashboardRichText.spec.ts**|5(2 skipped)|-|12.859s|
|✅|**dashboardScatterPlot.spec.ts**|1|-|7.861s|
|✅|**dashboardTiger.spec.ts**|12(6 skipped)|-|25.160s|
|✅|**dashboardTigerWithCharts.spec.ts**|2(1 skipped)|-|8.896s|
|✅|**dependentFilters.spec.ts**|6(4 skipped)|-|141.593s|
|✅|**dragDropAndMoveWidget.spec.ts**|4(2 skipped)|-|35.717s|
|✅|**headerSection.spec.ts**|4(2 skipped)|-|20.980s|
|✅|**hideFilters.spec.ts**|20|-|155.087s|
|✅|**insightOnDashboard.spec.ts**|9(4 skipped)|-|36.462s|
|✅|**multipleDateFilters.spec.ts**|5|-|37.365s|
|✅|**unknownVisualization.spec.ts**|1|-|5.879s|
|✅|**manyData.spec.ts**|2|-|11.973s|
|✅|**scatterPlot.spec.ts**|2|-|8.428s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-record-zuul/211/).

**Comment by pbenes** [comment]
extended test - tiger-cypress - isolated

**Review by ivanmjartan — APPROVED** [review]

**Pull request merged**
