### PR TITLE
Do not merge, for testing

### PR DESCRIPTION
**Pull request by pbenes**
---

Supported PR commands:

| Command                                               | Description                                                |
| ----------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                          | Re-run standard checks                                     |
| `extended check sonar`                                | SonarQube tests                                            |
| `extended check plugins`                              | Dashboard plugins tests                                    |
| `extended test - backstop`                            | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                |                                                            |
| `extended test - tiger-cypress - isolated <testName>` | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`   | Create a new recording for isolated Tiger tests.           |
| **E2E Cypress tests commands - BEAR**                 |                                                            |
| `extended test - cypress - isolated <testName>`       | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`         | Create a new recording for isolated Bear tests.            |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by pbenes** [comment]
extended test - tiger-cypress - isolated

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/103/ : FAILURE in 13m 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11300/ : SUCCESS in 6s

**Comment by pbenes** [comment]
extended test - cypress - isolated

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardDependentFilter.spec.ts**|4|-|60.0650s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.0770s|
|✅|**attributeFilterButton.spec.ts**|9|-|33.9780s|
|✅|**dateFilter.spec.ts**|9|-|14.3670s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|43.4390s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.6820s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|21.7480s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.7820s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.4470s|
|✅|**barChartDrilling.spec.ts**|4|-|6.4480s|
|✅|**dashboard.spec.ts**|9|-|70.5190s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.9880s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|50.7300s|
|✅|**dashboardDateRelated.spec.ts**|8|-|84.9300s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.1890s|
|✅|**dashboardKPI.spec.ts**|8|-|182.1760s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|178.9510s|
|✅|**dashboardDnD.spec.ts**|7|-|74.1280s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.8500s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.1720s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/381/).

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dashboardDependentFilter.spec.ts**|4|-|60.0650s|
|✅|**pivotTableSizing.spec.ts**|1|-|5.0770s|
|✅|**attributeFilterButton.spec.ts**|9|-|33.9780s|
|✅|**dateFilter.spec.ts**|9|-|14.3670s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|43.4390s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|17.6820s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|21.7480s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|17.7820s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|7.4470s|
|✅|**barChartDrilling.spec.ts**|4|-|6.4480s|
|✅|**dashboard.spec.ts**|9|-|70.5190s|
|✅|**headlineChartDrilling.spec.ts**|2|-|3.9880s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|50.7300s|
|✅|**dashboardDateRelated.spec.ts**|8|-|84.9300s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|7.1890s|
|✅|**dashboardKPI.spec.ts**|8|-|182.1760s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|178.9510s|
|✅|**dashboardDnD.spec.ts**|7|-|74.1280s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|7.8500s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|7.1720s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul-docker/381/).

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher/104/ : SUCCESS in 27m 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11302/ : SUCCESS in 12s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11299/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/13388/ : SUCCESS in 42m 37s

**Comment by pbenes** [comment]
extended test - backstop

**Comment by yenkins** [comment]
Link to Storybook test result: https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-backstop-tests/1962/artifact/libs/sdk-ui-tests/backstop/output/html-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11495/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/1/ : SUCCESS in 25m 55s

**Comment by pbenes** [comment]
extended test - backstop

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11497/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/2/ : FAILURE in 11m 20s

**Comment by pbenes** [comment]
extended test - cypress - integrated dashboardDateRelated

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11814/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/116/ : SUCCESS in 6m 33s

**Comment by pbenes** [comment]
extended test - cypress - integrated

**Comment by gdgate** [comment]
Build failed (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-oss-check/11815/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-pull-request-dispatcher-pipeline/117/ : FAILURE in 8m 25s

**Pull request closed without merging**
