### PR TITLE
TRIVIAL: Fix unstable drilling test

### PR DESCRIPTION
**Pull request by NghiLamGD**
---

Supported PR commands:

| Command                                                 | Description                                                |
| ------------------------------------------------------- | ---------------------------------------------------------- |
| `ok to test`                                            | Re-run standard checks                                     |
| `extended check sonar`                                  | SonarQube tests                                            |
| `extended check plugins`                                | Dashboard plugins tests                                    |
| `extended test - backstop`                              | BackstopJS tests                                           |
| **E2E Cypress tests commands - TIGER**                  |                                                            |
| `extended test - tiger-cypress - isolated <testName>`   | Run isolated tests running against recorded Tiger backend. |
| `extended test - tiger-cypress - record <testName>`     | Create a new recording for isolated Tiger tests.           |
| `extended test - tiger-cypress - integrated <testName>` | Run integrated tests against live backend                  |
| **E2E Cypress tests commands - BEAR**                   |                                                            |
| `extended test - cypress - isolated <testName>`         | Run isolated tests running against recorded Bear backend.  |
| `extended test - cypress - record <testName>`           | Create a new recording for isolated Bear tests.            |
| `extended test - cypress - integrated <testName>`       | Run integrated tests against live backend                  |

`<testName>` in cypress commands is used to filter specfiles. Example, to run record with BEAR backend

-   Against `dashboard.spec.ts` and `drilling.spec.ts`, execute command `extended test - cypress - record dashboard,drilling`
-   Against all specfiles, execute command `extended test - cypress - record` or `extended test - cypress - record *`

---

# PR Checklist

-   [ ] commit messages adhere to the [commit message guidelines](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#what-should-the-commits-look-like)
-   [ ] review was done by a Code owner [if necessary](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-tell-if-my-pull-request-needs-approval-by-a-code-owner) (if you think it is not necessary, explain the reasoning in the description or in a comment)
-   [ ] `check` passes
-   [ ] `extended test - backstop` passes
-   [ ] `extended test - tiger-cypress - record` to record new mapping files (Tiger BE)
-   [ ] `extended test - cypress - record` to record new mapping files (Bear BE)
-   [ ] `extended test - tiger-cypress - isolated` passes
-   [ ] `extended test - cypress - isolated` passes
-   [ ] `extended test - tiger-cypress - integrated` passes
-   [ ] `rush change` [was run if applicable](https://github.com/gooddata/gooddata-ui-sdk/blob/master/docs/contributing.md#how-do-i-describe-my-changes-for-the-changelog)

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Merge Failed.

Zuul merger could not merge this change into the base branch. This is most likely caused by merge conflicts. Please rebase the change and upload the rebased version. In case of further errors, contact the zuul administrator.

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Review by hungnguyenauto — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**dragDropAndMoveWidget.spec.ts**|3(1 skipped)|-|40.7510s|
|✅|**dashboardTiger.spec.ts**|9(4 skipped)|-|24.1300s|
|✅|**dashboardBasicActions.spec.ts**|2|-|15.3680s|
|✅|**headerSection.spec.ts**|4(1 skipped)|-|61.2430s|
|✅|**insightOnDashboard.spec.ts**|6(1 skipped)|-|41.5190s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/88/).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-ui-sdk-gate-PR3571

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by yenkins** [comment]
# ✨ Cypress test results ✨

## 🎉 Great news! Tests were successful.

|Status|Name|Tests|Failures|Time|
|:--:|:--|:--:|:--:|--:|
|✅|**headlineChartDrilling.spec.ts**|2|-|2.9210s|
|✅|**pivotTableSizingReset.spec.ts**|15|-|36.0390s|
|✅|**dateFilter.spec.ts**|9|-|11.7880s|
|✅|**barChartDrilling.spec.ts**|4|-|5.4790s|
|✅|**pivotTableRemoveOneAggregation.spec.ts**|1|-|5.8380s|
|✅|**attributeFilter.spec.ts**|1|-|6.2030s|
|✅|**pivotTableRemoveAllFromMutipleAggregation.spec.ts**|1|-|5.9460s|
|✅|**dashboardKPI.spec.ts**|8|-|136.3130s|
|✅|**dashboardFiltering.spec.ts**|18(2 skipped)|-|141.1200s|
|✅|**drilling.spec.ts**|7(2 skipped)|-|36.6890s|
|✅|**attributeFilterButtonParentChild.spec.ts**|3|-|12.5870s|
|✅|**attributeFilterButton.spec.ts**|13|-|47.4360s|
|✅|**dashboardDnD.spec.ts**|7|-|55.8380s|
|✅|**dashboard.spec.ts**|9|-|56.6740s|
|✅|**dashboardDateRelated.spec.ts**|8|-|63.4000s|
|✅|**dashboardDependentFilter.spec.ts**|8|-|85.2980s|
|✅|**pivotTableRemoveOneFromMutipleAggregation.spec.ts**|1|-|6.1420s|
|✅|**pivotTableSizing.spec.ts**|1|-|3.8900s|
|✅|**attributeFilterButtonWithSelection.spec.ts**|2|-|5.8330s|
|✅|**pivotTableAggregationsMenuAndAddTotal.spec.ts**|5|-|17.7900s|
|✅|**parentChildFiltersWithPlaceholders.spec.ts**|3|-|15.7270s|

You can find full report [here](https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/465/).

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-tiger-isolated-zuul/88/ : SUCCESS in 8m 31s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-fossa-scanning-zuul/416/ : FAILURE in 2m 25s (non-voting)
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-unit-tests/14044/ : SUCCESS in 6m 50s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-merge-compliance-check/3689/ : SUCCESS in 18s
- https://checklist.intgdc.com/job/compliance/job/gooddata-ui-sdk-sonarqube-scan-zuul-gate/2532/ : SUCCESS in 13m 12s
- https://checklist.intgdc.com/job/gooddata-ui-sdk/job/gooddata-ui-sdk-cypress-bear-isolated-zuul/465/ : SUCCESS in 21m 06s (non-voting)

**Pull request merged**
